### ISSUE TITLE
Can't restart instance if Minecraft crashed

### ISSUE THREAD

**Issue by Azenet** [ATLauncher/ATLauncher#15]
It's impossible to restart an instance if Minecraft just crashed (and closed).

```
Exception in thread "Thread-3" java.lang.IllegalThreadStateException: process hasn't exited
        at java.lang.UNIXProcess.exitValue(UNIXProcess.java:217)
        at com.atlauncher.data.Instance$2.run(Instance.java:575)
```

**Comment by Quirkymender09** [comment]
com.atlauncher.data.Instance$2.run(Instance.java:1154) that is what i got but i don`t get it

**Comment by kAlz** [comment]
I just had the mistake happen to me
