### ISSUE TITLE
Random java.lang.ArrayIndexOutOfBoundsException when installing instances

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#202]
As the title states, there are random java.lang.ArrayIndexOutOfBoundsException with no stacktraces appearing when installing an instance which causes issues and makes the launcher no longer functional as new instances cannot be installed once this happens.

**Comment by RyanTheAllmighty** [comment]
This also occurs on the current version of the launcher and will randomly occur even when not trying to install an instance. Just starting it up and leaving it there will cause it to occur sometimes.

**Comment by RyanTheAllmighty** [comment]
The ExceptionStrainer is catching the exception, but all that it's printing is 'java.lang.ArrayIndexOutOfBoundsException' to the console and that's it.

There is no stack trace info or anything.

**Comment by RyanTheAllmighty** [comment]
Removing the unhandled exception handler will result in the following:

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException
```

**Comment by RyanTheAllmighty** [comment]
If I add the following to my JVM arguments it seems to stop the issue for occuring at all for some reason

```
-XX:-OmitStackTraceInFastThrow
```

**Comment by RyanTheAllmighty** [comment]
I find it very odd that the addition of this JVM argument would stop the issue from happening at all. Like as soon as I remove it, 50% chance of the issue being there, then I add this JVM argument in and I can start it up 100 times and not get it once...

I am thoroughly confused. If you have any ideas at all @s0cks please let me know.

**Comment by RyanTheAllmighty** [comment]
Seems when it occurs, trying to create an instance of a pack with optional mods it won't work, but packs where there are no optional mods, it's fine

**Comment by RyanTheAllmighty** [comment]
Actually that above seems to only occur when an instance of the same name already exists and causes the error when it tries to bring up the dialog about there already being an instance of the same name

**Comment by RyanTheAllmighty** [comment]
I don't know if that was the issue or not, but that seems to of fixed it occurring from what I can see at least in the master branch

**Comment by RyanTheAllmighty** [comment]
Nope nevermind

**Comment by RyanTheAllmighty** [comment]
```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog$2$1.done(InstanceInstallerDialog.java:328)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog$2.actionPerformed(InstanceInstallerDialog.java:507)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:523)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:78)
	at com.atlauncher.gui.card.PackCard$1.actionPerformed(PackCard.java:131)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by RyanTheAllmighty** [comment]
I'm thinking this is the fault of the console/logging as when it occurs, any use of the console will just cause more and more of the same exception to be thrown.

I'm not 100% sure yet, but the weird behaviour of the console after the issue occurs makes me think it **MAY** have something to do with it.

**Comment by RyanTheAllmighty** [comment]
Okay it's not my Java install, just did a fresh install with the same issue reoccuring

**Comment by RyanTheAllmighty** [comment]
Okay I definately think this is to do with the current logging.

When I don't start the queue the issue doesn't happen

**Comment by RyanTheAllmighty** [comment]
I think it may have something to do with when it writes to the ATLauncher Console, as when those lines are removed from the LogEvent class the issue again disappears.

**Comment by reteo** [comment]
When attempting to install a recent test modpack, I received an almost [identical error](http://paste.atlauncher.com/view/765f028b).  The published pack works without a flaw, however.

**Comment by reteo** [comment]
In my case, this seems to happen when using the "linked" attribute to connect a visible mod with a hidden one; once the links to hidden mods were removed, the error went away.

**Comment by flaw600** [comment]
So we need to fix the LogEvent class?

**Comment by RyanTheAllmighty** [comment]
Possibly, I've not looked at this issue for a while, but if I posted it in this issue then I have no reason to believe it to have changed

**Comment by flaw600** [comment]
If you haven't noticed it lately, since this is the only issue under this milestone, can we push this to 3.3.0.0? That way 3.2.3.2 can go to testing and then release

**Comment by RyanTheAllmighty** [comment]
I'll need to investigate to make sure if it's still an issue.

**Comment by reteo** [comment]
I don't know if this is relevant, but try linking a mod to a hidden mod; If I recall correctly, that was what caused the above error for me.

**Comment by RyanTheAllmighty** [comment]
That doesn't seem to be the issue @reteo. I'm not getting any error in that situation with the below XML:

```xml
<version>
    <pack>
        <minecraft>1.7.10</minecraft>
        <version>1.0.0</version>
        <noconfigs>true</noconfigs>
    </pack>
    
    <mods>
        <mod name="Parent" version="1.0.0" url="https://download.nodecdn.net/containers/atl/launcher/json/packs.json" file="parent.json" hidden="yes" download="direct" optional="yes" type="mods" website="https://www.atlauncher.com" description="Parent" />
        <mod name="Child" version="1.0.0" url="https://download.nodecdn.net/containers/atl/launcher/json/packs.json" file="child1.json" download="direct" depends="Parent" optional="yes" type="mods" website="https://www.atlauncher.com" description="Child" />
    </mods>
</version>
```

**Comment by RyanTheAllmighty** [comment]
Okay I'm not seeing this issue occur anymore in any of the ways it was occuring before.

I'm going to remove the 3.2.3.2 milestone and close this since it seems to not be an issue anymore.
