### ISSUE TITLE
Issues with saving Settings

### ISSUE THREAD

**Issue by s0cks** [ATLauncher/ATLauncher#211]
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 41 column 3 path $
    at com.google.gson.Gson.assertFullConsumption(Gson.java:786)
    at com.google.gson.Gson.fromJson(Gson.java:749)
    at com.atlauncher.nio.JsonFile.convert(JsonFile.java:85)
    at com.atlauncher.nio.JsonFile.convert(JsonFile.java:76)
    at com.atlauncher.managers.SettingsManager.loadSettings(SettingsManager.java:41)
    at com.atlauncher.Loader.<init>(Loader.java:91)
    at com.atlauncher.App.main(App.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 41 column 3 path $
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
    at com.google.gson.Gson.assertFullConsumption(Gson.java:782)
    ... 11 more
```

**Comment by RyanTheAllmighty** [comment]
Yeah somewhere along the way somewhere there is an issue where it saves the settings but not fully, so it makes invalid JSON

**Comment by flaw600** [comment]
@s0cks can you investigate what exactly is being mis saved?

**Comment by s0cks** [comment]
Just set the parser to lenient it should be fine after that.

**Comment by flaw600** [comment]
It was you who brought up issue lol, you fix it

**Comment by flaw600** [comment]
@s0cks in case you get free time :) ^

**Comment by 7osCraft** [comment]
I can work in it and fix it if you want

**Comment by RyanTheAllmighty** [comment]
Closing as it's old and likely not relevant
