### ISSUE TITLE
Java 9 Issue

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#323]
Logs:

```
[03/12/2017 19:47:10 PM] [ERROR]java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @f58853c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at com.atlauncher.utils.Utils.getSystemRam(Utils.java:477)
	at com.atlauncher.utils.Utils.getMaximumRam(Utils.java:506)
	at com.atlauncher.App.main(App.java:311)
```

**Comment by RyanTheAllmighty** [comment]
Show some error to users using Java 9

**Comment by RyanTheAllmighty** [comment]
Closed due to existing ticket: https://github.com/ATLauncher/ATLauncher/issues/294
