### ISSUE TITLE
logging in

### ISSUE THREAD

**Issue by MasterDJRE** [ATLauncher/ATLauncher#345]
this appears in console whenever I try to log in:
] java.lang.UnsupportedClassVersionError: com/mojang/authlib/exceptions/AuthenticationUnavailableException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.atlauncher.gui.tabs.AccountsTab$9.run(AccountsTab.java:301)
can some one help me?

**Comment by RyanTheAllmighty** [comment]
You need to upgrade to Java 8
