### ISSUE TITLE
Broken with Java 14

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#383]
Java 14 just released, and this removed `java.util.jar.Pack200` things so some things that are using it will fail.

```
[26/3/2020 14:23:10 pm] java.lang.NoClassDefFoundError: java/util/jar/Pack200
        at com.atlauncher.utils.Utils.unpackFile(Utils.java:1516)
        at com.atlauncher.utils.Utils.unXZPackFile(Utils.java:1414)
        at com.atlauncher.network.Download.runPostProcessors(Download.java:583)
        at com.atlauncher.network.Download.downloadFile(Download.java:573)
        at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:114)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 8 more
```

**Comment by RyanTheAllmighty** [comment]
Released with version 3.3.4.5
