### ISSUE TITLE
App crashes on launch on Java >= 9

### ISSUE THREAD

**Issue by homemmakako** [ATLauncher/ATLauncher#395]
The ATLauncher jar, built upon master as of f7eb98196deca0a25fe10bb9c60b9c7853532c85, when attempting to launch on Linux (Manjaro KDE), crashes with NullPointer. This happens because of it not being able to load any of the fonts. The same .jar, same commit, works fine on windows. It should be noted, both were built with jdk 8.

**To Reproduce**

1. Clone repository
2. Run `gradlew build`
3. Execute the .jar file

**System Info**
- OS: Linux - Manjaro KDE
- JDK 8

**Logs**
[Linux Log](https://paste.atlauncher.com/view/e6237d73)

**Comment by RyanTheAllmighty** [comment]
Yeah someone else had this issue on Windows and is why I haven't made a new release yet.

The issue is it cannot load the resources it needs from the jar file (things like fonts and a particular css file used for the news tab).

Not sure what causes it, I just know the issue exists

**Comment by jamierocks** [comment]
You're not running ATLauncher under Java 8.

> java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)

**Comment by RyanTheAllmighty** [comment]
Yeah can see that in the logs:

`[16/07/2020 17:20:53 PM] Java Version: Launcher: Java 14 (14.0.1), Minecraft: Java 8 (1.8.0_252)`

It shouldn't be an issue though with Java 14 AFAIK. Maybe I need to test with 14, maybe something happened with 14

**Comment by homemmakako** [comment]
> You're not running ATLauncher under Java 8.

Yeah my bad, I simply assumed the launcher would use the java version in the java_home path.

So, testing with diferent java versions: java 8 works, java 11 and 14 do not.

**Comment by RyanTheAllmighty** [comment]
It will use whichever java is used to execute the jar file. So using `java -jar` on the command line or right clicking and running in your file browser it will use that java version which may not always be whats in your `java_home` path

**Comment by RyanTheAllmighty** [comment]
If you can provide logs from Java 11 that will help debug the issue @homemmakako

**Comment by homemmakako** [comment]
Sure thing, [here you go](https://paste.atlauncher.com/view/43523737), though the error seems to be the same. 

Aparently it was a change made to getResource in java 9 (?)
[Possibly related](https://stackoverflow.com/questions/54021754/why-does-the-getresource-method-return-null-in-jdk-11)

**Comment by jamierocks** [comment]
```
com.atlauncher.exceptions.ChunkyException: java.lang.NullPointerException
	at com.atlauncher.utils.Resources.makeStyleSheet(Resources.java:72)
	at com.atlauncher.gui.tabs.NewsTab$1.<init>(NewsTab.java:48)
	at com.atlauncher.gui.tabs.NewsTab.<init>(NewsTab.java:46)
	at com.atlauncher.gui.LauncherFrame.setupTabs(LauncherFrame.java:168)
	at com.atlauncher.gui.LauncherFrame.<init>(LauncherFrame.java:89)
	at com.atlauncher.App.lambda$main$6(App.java:428)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at com.atlauncher.utils.Resources.makeStyleSheet(Resources.java:64)
	... 18 more
```

Fedora 33, Java 11.0.7 ([full log](https://gist.github.com/jamierocks/c4c6f2bcbfc5d74708d5bee0e5392582))

**Comment by jamierocks** [comment]
> Aparently it was a change made to getResource in java 9 (?)

Yes, modules do change how resources work.

**Comment by RyanTheAllmighty** [comment]
Very odd. I've not had any other issues come up with the current launcher and newer Java versions which use getResource. Strange

**Comment by jamierocks** [comment]
This is a simple patch, I'll make a PR shortly :)

**Comment by RyanTheAllmighty** [comment]
Issue is fixed thanks to @jamierocks this will go out with 3.3.6.0 of the launcher
