### ISSUE TITLE
Error loading instances

### ISSUE THREAD

**Issue by pickerstick** [ATLauncher/ATLauncher#464]
**Describe the bug**
Yesterday I played minecraft normally but today the instances tab are empty!

PS:I cleared the downloads folder.Should not cause the bug.Early 2020 I cleared it and didn't cause any bugs.

**Expected behavior**
Should load instances.

**Logs**
Link here:https://paste.atlauncher.com/view/161e75eb
If not avaliable,see here:
```[04/04/2021 09:49:23 AM] Organising filesystem
[04/04/2021 09:49:23 AM] ATLauncher Version: 3.4.3.1
[04/04/2021 09:49:23 AM] Java Version: Launcher: Java 16 (16), Minecraft: Java 8 (1.8.0_51)
[04/04/2021 09:49:23 AM] Java Path: **USERSDIR**\runtimes\1.8.0_51
[04/04/2021 09:49:23 AM] 64 Bit Java: true
[04/04/2021 09:49:23 AM] RAM Available: 16307MB
[04/04/2021 09:49:23 AM] Launcher Directory: **USERSDIR**
[04/04/2021 09:49:24 AM] GPU: NVIDIA GeForce GTX 1660 SUPER (NVIDIA (0x10de)) DriverVersion=27.21.14.6589 4095MB VRAM
[04/04/2021 09:49:24 AM] CPU: 4 cores/8 threads
[04/04/2021 09:49:24 AM] Operating System: Windows (6.1 SP1 build 7601)
[04/04/2021 09:49:24 AM] Bitness: 64
[04/04/2021 09:49:24 AM] Uptime: 3021
[04/04/2021 09:49:24 AM] Manufacturer: Microsoft
[04/04/2021 09:49:24 AM] Disk: C:\(Windows 7) (33431 MB Free)
[04/04/2021 09:49:24 AM] Disk: D:\(Windows10) (80096 MB Free)
[04/04/2021 09:49:24 AM] Disk: E:\ (278305 MB Free)
[04/04/2021 09:49:24 AM] Disk: F:\ (370706 MB Free)
[04/04/2021 09:49:24 AM] Disk: G:\(Soft) (37567 MB Free)
[04/04/2021 09:49:24 AM] Disk:  (0 MB Free)
[04/04/2021 09:49:24 AM] Showing splash screen and loading everything
[04/04/2021 09:49:24 AM] Checking for updated files!
[04/04/2021 09:49:32 AM] Finished downloading updated files!
[04/04/2021 09:49:32 AM] Failed to load instance in the folder **USERSDIR**\instances\Farmin
[04/04/2021 09:49:32 AM] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @6aba2b86

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)

	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)

	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.Gson.fromJson(Gson.java:931)

	at com.google.gson.Gson.fromJson(Gson.java:870)

	at com.atlauncher.managers.InstanceManager.loadInstances(InstanceManager.java:67)

	at com.atlauncher.Launcher.loadEverything(Launcher.java:125)

	at com.atlauncher.App.main(App.java:354)

[04/04/2021 09:49:32 AM] Failed to load instance in the folder **USERSDIR**\instances\SkyFactory4
[04/04/2021 09:49:32 AM] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @6aba2b86

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)

	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)

	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.Gson.fromJson(Gson.java:931)

	at com.google.gson.Gson.fromJson(Gson.java:870)

	at com.atlauncher.managers.InstanceManager.loadInstances(InstanceManager.java:67)

	at com.atlauncher.Launcher.loadEverything(Launcher.java:125)

	at com.atlauncher.App.main(App.java:354)

[04/04/2021 09:49:32 AM] Failed to load instance in the folder **USERSDIR**\instances\TwilightForest
[04/04/2021 09:49:32 AM] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @6aba2b86

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)

	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)

	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.Gson.fromJson(Gson.java:931)

	at com.google.gson.Gson.fromJson(Gson.java:870)

	at com.atlauncher.managers.InstanceManager.loadInstances(InstanceManager.java:67)

	at com.atlauncher.Launcher.loadEverything(Launcher.java:125)

	at com.atlauncher.App.main(App.java:354)

[04/04/2021 09:49:32 AM] Failed to load instance in the folder **USERSDIR**\instances\VanillaMcForMySelf
[04/04/2021 09:49:32 AM] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @6aba2b86

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)

	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)

	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.Gson.fromJson(Gson.java:931)

	at com.google.gson.Gson.fromJson(Gson.java:870)

	at com.atlauncher.managers.InstanceManager.loadInstances(InstanceManager.java:67)

	at com.atlauncher.Launcher.loadEverything(Launcher.java:125)

	at com.atlauncher.App.main(App.java:354)

[04/04/2021 09:49:32 AM] Failed to load instance in the folder **USERSDIR**\instances\VanillaMinecraft
[04/04/2021 09:49:32 AM] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @6aba2b86

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)

	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)

	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.Gson.fromJson(Gson.java:931)

	at com.google.gson.Gson.fromJson(Gson.java:870)

	at com.atlauncher.managers.InstanceManager.loadInstances(InstanceManager.java:67)

	at com.atlauncher.Launcher.loadEverything(Launcher.java:125)

	at com.atlauncher.App.main(App.java:354)

[04/04/2021 09:49:32 AM] Failed to load instance in the folder **USERSDIR**\instances\VanillaMinecraftEARLY
[04/04/2021 09:49:32 AM] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @6aba2b86

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)

	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)

	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)

	at com.google.gson.Gson.getAdapter(Gson.java:458)

	at com.google.gson.Gson.fromJson(Gson.java:931)

	at com.google.gson.Gson.fromJson(Gson.java:870)

	at com.atlauncher.managers.InstanceManager.loadInstances(InstanceManager.java:67)

	at com.atlauncher.Launcher.loadEverything(Launcher.java:125)

	at com.atlauncher.App.main(App.java:354)

[04/04/2021 09:49:32 AM] Launcher finished loading everything
[04/04/2021 09:49:32 AM] Launcher opening
[04/04/2021 09:49:32 AM] Made By Bob*
[04/04/2021 09:49:32 AM] *(Not Actually)
[04/04/2021 09:49:32 AM] Setting up Bottom Bar
[04/04/2021 09:49:33 AM] Finished Setting up Bottom Bar
[04/04/2021 09:49:33 AM] Setting up Tabs
[04/04/2021 09:49:33 AM] Finished Setting up Tabs
[04/04/2021 09:49:33 AM] Showing Launcher
[04/04/2021 09:51:36 AM] Log uploaded and link copied to clipboard: https://paste.atlauncher.com/view/161e75eb
```

**System information (please complete the following information, or remove if not applicable):**

- OS Windows 7
- Java Version: Java 8

**Comment by RyanTheAllmighty** [comment]
My guess is it's caused by your Java 16 install.

Java 16 has not been validated against ATLauncher, so may be causing the issue.

Please uninstall it, restart, then install Java 8 from https://atl.pw/java8download to see if it fixes the issue

**Comment by pickerstick** [comment]
Did I have Java 16?

**Comment by pickerstick** [comment]
Oh,yes,JDK 16.

**Comment by RyanTheAllmighty** [comment]
Yes. Second line in the log:

`[04/04/2021 09:49:23 AM] Java Version: Launcher: Java 16 (16), Minecraft: Java 8 (1.8.0_51)`

**Comment by pickerstick** [comment]
I do have Java 8.

> Minecraft:Java 8(1.8.0_51)

**Comment by pickerstick** [comment]
Fixed!Thanks for your help!
