### ISSUE TITLE
Trying to disable a mod placed in a subfolder doesn't work

### ISSUE THREAD

**Issue by SonoSooS** [ATLauncher/ATLauncher#486]
**Describe the bug**
Attempting to disable a mod explicitly moved to a subfolder in the mods folder will cause an exception to be printed in the console with nothing changed.

**To Reproduce**

1. Add a mod from the filesystem into the modpack from the "Edit Mods" interface
2. Close ATLauncher
3. Edit instance.json in a way, so the newly added mod's file field reflects the mod's relative path to the mods folder (eg. changing `"file": "modname.jar"` to `"file": "1.7.10/modname.jar"`)
4. Reopen ATLauncher
5. Try to disable the mod in the "Edit Mods" interface whose entry was modified in instance.json

**Expected behavior**
"modname.jar" to be moved to "disabledmods/1.7.10/modname.jar"

**Logs**

```
[12/07/2021 01:32:37 AM] java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at com.atlauncher.utils.Utils.copyFile(Utils.java:280)
	at com.atlauncher.utils.Utils.moveFile(Utils.java:233)
	at com.atlauncher.data.DisableableMod.disable(DisableableMod.java:240)
	at com.atlauncher.gui.dialogs.EditModsDialog.disableMods(EditModsDialog.java:533)
	at com.atlauncher.gui.dialogs.EditModsDialog.lambda$setupComponents$10(EditModsDialog.java:289)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	[AWT/Swing stacktrace truncated]
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at com.atlauncher.gui.dialogs.EditModsDialog.<init>(EditModsDialog.java:109)
	at com.atlauncher.gui.card.InstanceCard.lambda$addActionListeners$21(InstanceCard.java:418)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	[AWT/Swing stacktrace truncated]
[12/07/2021 01:32:37 AM] Couldn't move file **USERSDIR**\instances\mypak\mods\1.7.10\CodingLib-0.2.8b50.jar to **USERSDIR**\instances\mypak\disabledmods\1.7.10\CodingLib-0.2.8b50.jar
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7823099/125213358-67e44000-e2b2-11eb-8909-a6290e09a306.png)

**System information (please complete the following information, or remove if not applicable):**

- ATLauncher Version: 3.4.4.6
- OS (including distro/version): Windows (10.0 build 15063)
- Java Version: Java 8 (1.8.0_291)

**Additional context**
I tried to do this because there is no option to add a mod into the `<minecraftversion>` folder in the "Edit Mods" UI, and some mods (like in this example, Coding Lib) need to be placed in the "1.7.10" subfolder in the mods folder for it to work at all.

**Comment by RyanTheAllmighty** [comment]
Ah so there should be a way to add them to the `mods/{mcversion}` folder, the launcher does that for some packs, will just need to add it to the dropdown when adding a mod manually.

But as for when you manually move/rename a file in your OS, the launcher can't know about this. It doesn't get or know when files are moved/renamed, so in regards to that part, there's nothing we can really do, but adding the option for "dependency" mods which go in the `mods/{mcversion}`.

**Comment by SonoSooS** [comment]
By the way you phrased it, it sounds like it's already semi-supported. Do you know a temporary workaround for this, or am I misunderstanding?

As for "nothing you can do", I'm pretty sure it can be "fixed" by creating the directory tree recursively before moving the file. Although in most cases (other than 1-2 really esotericly programmed mods) no recursive search is needed, and you can just split the path by checking if the filename contains a `/`, and create the subfolder accordingly.
Although I guess instance.json is not something I'm supposed to be editing by hand in the first place, so in that case "nothing you can do" holds true.

But yeah, this bug report is also a feature suggestion.

Even though I don't really like "dependency mod" name, I can't find any better alternative which is not misleading. Even though this folder is no different from the regular mods folder, its earlier search priority allows mod creators to make an intermediary between a regular mod and a coremod without actually going down the (deprecated?) coremod route, so naming these "library coremods" is quite misleading, even though it's not that far off their functional truth.
And even then, I'm a developer with no UX/UIX knowledge, so I don't know which is better for the end-user 😄.

My only suggestion related to that would be to add in brackets what the option means - if it doesn't break the "design language" of the UI too much - so people won't have to look up the documentation to know if a mod explicitly goes to the 1.7.10 folder, and they don't know what "dependency" mod means. Sort of like this:
>      Dependency mod (1.7.10 folder)
