### ISSUE TITLE
macOS/OSX App Issues

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#502]
There seems to be some issues with the OSX app itself not launching instances in Big Sur (specifically was an issue with FTB Academy 1.16) and there is also some issue where the jar app is writing files into a temp directory such as `/private/var/folders/qv/k8cn8m4s6tz08xyy7sglq1y40000gn/T/hsperfdata_username` which is removed after a reboot.

**Comment by RyanTheAllmighty** [comment]
Issues launching on moteray using the app. Wen't away with the jar version of the launcher:

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11/23/21 8:04 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_74] {}
-- MOD industrialforegoing --
Details:
	Caused by 0: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
		at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222) ~[core-3.6.3.jar:?] {}
		at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
		at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138) ~[core-3.6.3.jar:?] {}
		at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.load(SimpleCommentedFileConfig.java:38) ~[core-3.6.3.jar:?] {}
		at com.hrznstudio.titanium.module.ModuleController.onInit(ModuleController.java:68) ~[?:3.2.8.4] {re:classloading}
		at com.hrznstudio.titanium.module.ModuleController.<init>(ModuleController.java:45) ~[?:3.2.8.4] {re:classloading}
		at com.buuz135.industrial.IndustrialForegoing.<init>(IndustrialForegoing.java:104) ~[?:3.2.14.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}

	Mod File: industrial-foregoing-1.16.5-3.2.14.3-9.jar
	Failure message: Industrial Foregoing (industrialforegoing) has failed to load correctly
		com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
	Mod Version: 3.2.14.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.nio.file.NoSuchFileException: config/industrialforegoing/modules.toml
Stacktrace:
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_74] {}
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_74] {}
	at java.nio.file.Files.createFile(Files.java:632) ~[?:1.8.0_74] {}
	at com.electronwill.nightconfig.core.file.FileNotFoundAction.lambda$static$0(FileNotFoundAction.java:34) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:215) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.load(SimpleCommentedFileConfig.java:38) ~[core-3.6.3.jar:?] {}
	at com.hrznstudio.titanium.module.ModuleController.onInit(ModuleController.java:68) ~[?:3.2.8.4] {re:classloading}
	at com.hrznstudio.titanium.module.ModuleController.<init>(ModuleController.java:45) ~[?:3.2.8.4] {re:classloading}
	at com.buuz135.industrial.IndustrialForegoing.<init>(IndustrialForegoing.java:104) ~[?:3.2.14.3] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}


-- MOD titanium --
Details:
	Caused by 0: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
		at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222) ~[core-3.6.3.jar:?] {}
		at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
		at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138) ~[core-3.6.3.jar:?] {}
		at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.load(SimpleCommentedFileConfig.java:38) ~[core-3.6.3.jar:?] {}
		at com.hrznstudio.titanium.module.ModuleController.onInit(ModuleController.java:68) ~[?:3.2.8.4] {re:classloading}
		at com.hrznstudio.titanium.Titanium.onInit(Titanium.java:109) ~[?:3.2.8.4] {re:classloading}
		at com.hrznstudio.titanium.module.ModuleController.<init>(ModuleController.java:45) ~[?:3.2.8.4] {re:classloading}
		at com.hrznstudio.titanium.Titanium.<init>(Titanium.java:90) ~[?:3.2.8.4] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}

	Mod File: titanium-1.16.5-3.2.8.4-10.jar
	Failure message: Titanium (titanium) has failed to load correctly
		com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
	Mod Version: 3.2.8.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.nio.file.NoSuchFileException: config/titanium/modules.toml
Stacktrace:
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_74] {}
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_74] {}
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_74] {}
	at java.nio.file.Files.createFile(Files.java:632) ~[?:1.8.0_74] {}
	at com.electronwill.nightconfig.core.file.FileNotFoundAction.lambda$static$0(FileNotFoundAction.java:34) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:215) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.load(SimpleCommentedFileConfig.java:38) ~[core-3.6.3.jar:?] {}
	at com.hrznstudio.titanium.module.ModuleController.onInit(ModuleController.java:68) ~[?:3.2.8.4] {re:classloading}
	at com.hrznstudio.titanium.Titanium.onInit(Titanium.java:109) ~[?:3.2.8.4] {re:classloading}
	at com.hrznstudio.titanium.module.ModuleController.<init>(ModuleController.java:45) ~[?:3.2.8.4] {re:classloading}
	at com.hrznstudio.titanium.Titanium.<init>(Titanium.java:90) ~[?:3.2.8.4] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1585170624 bytes (1511 MB) / 3007840256 bytes (2868 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
```

**Comment by GhostIsBeHere** [comment]
ATlauncher will mostly hang on MacOS Mojave when clicking the "View", "Open Folder", "Open on Curseforge/Modrinth", "Show in file explorer", etc. No log messages, just a pure hang that requires Command+Q. It will sometimes work and I don't know what changes.

**Comment by dannydjdk** [comment]
I found a workaround that may provide some insight.

1. Set up an instance in ATLauncher with a mod that triggers this bug (CraftTweaker for example).
2. Set up an instance in the vanilla launcher using the same forge version.
3. Set the game directory of the vanilla launcher instance to the instance directory within ATLauncher.

This allows me to continue using ATLauncher to manage my packs while working around this issue with the vanilla launcher.

This narrows down the issue to a launch problem, and not an instance creation/management problem in case that wasn't already clear. Another piece of insight discovered in the CraftTweaker issue linked above is that the problem does not exist in the Fabric version of CraftTweaker which does the same thing (attempts to create a custom log file in the logs directory).

My guess is that it has something to do with how the file io is threaded. Forge mods launched through ATLauncher must be threading io in a way that triggers the OS to block the operation with its overzealous security features. I have seen similar issues with other java apps such as https://github.com/TheRandomLabs/ChangelogGenerator. Launching that app directly from the finder would result in failed load. The workaround was to launch it through the terminal. Then the OS would ask if you want to allow the terminal access to the file system.

 I hope that helps! Also, here's the latest.log: https://pastebin.com/Q8U5mceQ

**Comment by RyanTheAllmighty** [comment]
Alright so I've rented out a cloud based M1 Mac to test out some things, going to make some notes here with the findings and things I want to do going forward:

- [ ] The icon for the launcher doesn't match the style of the OS and sticks out. Should look at some design guidelines for OSX and follow them (https://user-images.githubusercontent.com/1723537/159118456-8a36f6fb-7abf-4831-b900-6f622f7e4e0f.png)
- [ ] There's still the issue of not a trusted developer when first launching the application (https://user-images.githubusercontent.com/1723537/159118527-670f8ce9-d72e-406f-bf28-cb3fd6808656.png). As well as OSX asking for permission for "bash" to access things. The website should have a guide to running the app similar to how the Setup for Windows does to just explain it
- [ ] Or alternatively instead of the above, maybe we can package the launcher as a dmg and then provide instructions within the dmg window. This will get people to install the app into the Applications directory as well which is more ideal

**Comment by RyanTheAllmighty** [comment]
As for the root issue which seems to be some file permission/security issues causing the crashes with certain mods, I can replicate it, happens when running the app, but when running the Jar from the terminal, no issue. Even just double clicking the jar file provides no issue.

I've given the app itself full disk access as well as the apps startup script and the JRE runtime used for launching Minecraft and no luck, same issue occurs.

So I'm entirely at a loss as to what the potential solution is, other than to just run the jar file which really isn't a solution.

My only other hunch is that it's due to something with how the application is packaged that is causing it, but I think that might be a stretch.

**Comment by bevv10** [comment]
@RyanTheAllmighty i really hate to be that guy that cant figure computer stuff out on his own but i cant seem to get it to work. i downloaded the java 8 that was requested when i first booted up. is there a different jar version i was suppose to use?

**Comment by RyanTheAllmighty** [comment]
This isn't support for the launcher. If you want support for the launcher, please visit our [Discord](https://atl.pw/discord) in the `#launcher-support` room

**Comment by whitebear60** [comment]
Got an issue with mod configs when using macOS app bundles, so the game crash when trying to join the server or world, making the app bundle unusable in the current state. Moving launcher files to `~/Library/Application Support/ATLauncher` won't help either.
[To view the crashlog, click here](https://discord.com/channels/117047818136322057/193303867180449794/1061995299821862992)

**Comment by RyanTheAllmighty** [comment]
Using [install4j](https://www.ej-technologies.com/products/install4j/overview.html) to build the app bundle resolves the issue, but the software is a paid one and is quite expensive, so it's not a solution unfortunately.

My hunch is it's the `universalJavaApplicationStub` causing the issue somehow
