### ISSUE TITLE
Issues running launcher - jawt.dll already loaded in another classloader

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#505]
Seen a few people on Discord now with the below issue:

```
java.lang.UnsatisfiedLinkError: Native Library C:\Program Files\Java\jre1.8.0_301\bin\jawt.dll already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at com.formdev.flatlaf.ui.FlatWindowsNativeWindowBorder.getInstance(FlatWindowsNativeWindowBorder.java:96)
	at com.formdev.flatlaf.ui.FlatNativeWindowBorder.initialize(FlatNativeWindowBorder.java:270)
	at com.formdev.flatlaf.ui.FlatNativeWindowBorder.isSupported(FlatNativeWindowBorder.java:68)
	at com.formdev.flatlaf.ui.FlatNativeWindowBorder.install(FlatNativeWindowBorder.java:76)
	at com.formdev.flatlaf.ui.FlatRootPaneUI.installNativeWindowBorder(FlatRootPaneUI.java:179)
	at com.formdev.flatlaf.ui.FlatRootPaneUI.installUI(FlatRootPaneUI.java:101)
	at javax.swing.JComponent.setUI(Unknown Source)
	at javax.swing.JRootPane.setUI(Unknown Source)
	at javax.swing.JRootPane.updateUI(Unknown Source)
	at javax.swing.JRootPane.<init>(Unknown Source)
	at javax.swing.JWindow.createRootPane(Unknown Source)
	at javax.swing.JWindow.windowInit(Unknown Source)
	at javax.swing.JWindow.<init>(Unknown Source)
	at javax.swing.JWindow.<init>(Unknown Source)
	at com.atlauncher.gui.SplashScreen.<init>(SplashScreen.java:44)
	at com.atlauncher.App.main(App.java:310)
```

Seems to be caused be a recentish update and the people having the issue, when asked, confirmed they checked the install Java option on the setup.

Looked at the FlatLaf repo and couldn't see any issues there around this, as that's the cause. I have yet to find a way to replicate this reliably, so may need to downgrade FlatLaf if this starts to come up more often, but for right now seems to be quite rare.

Looking at the FlatLaf code, it looks like this `jawt.dll` is only loaded on <= Java 8 and Windows 10:

https://github.com/JFormDesigner/FlatLaf/blob/5ebfb4fac014142ec3eaa207ad459456fbd13c21/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatWindowsNativeWindowBorder.java#L85-L109

Might be able to bump the setups Java version to a higher version now that Minecraft uses bundled jres now and be fine.

**Comment by RyanTheAllmighty** [comment]
Adding `UIManager.put( "TitlePane.useWindowDecorations", false );` might be the fix. It disables the special window decorations for each OS makes it look a little different in the title bar, nothing major. Definitely prefer it before, but not a big loss.

Before:
![image](https://user-images.githubusercontent.com/1723537/131929624-b5ca862e-9922-46bc-a6ed-37d87fcafb1e.png)

After:
![image](https://user-images.githubusercontent.com/1723537/131929661-75856bde-f374-4081-bfa8-9426cef07754.png)

**Comment by RyanTheAllmighty** [comment]
That wasn't the issue by the way. Will need to find some way to replicate this reliably to build a fix for it
