### ISSUE TITLE
Use Multiple Ports For Microsoft OAuth Login

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#535]
Catch this exception and then pool through a bunch of different ports until one works. I don't see this often, at least 1 time, but would be good to cover regardless

```
[08/12/2021 21:55:12 PM] Error starting web server for Microsoft login
[08/12/2021 21:55:12 PM] java.net.BindException: Address already in use: JVM_Bind
[08/12/2021 21:55:12 PM] 	at java.net.TwoStacksPlainSocketImpl.socketBind(Native Method)
[08/12/2021 21:55:12 PM] 	at java.net.TwoStacksPlainSocketImpl.socketBind(TwoStacksPlainSocketImpl.java:137)
[08/12/2021 21:55:12 PM] 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[08/12/2021 21:55:12 PM] 	at java.net.TwoStacksPlainSocketImpl.bind(TwoStacksPlainSocketImpl.java:110)
[08/12/2021 21:55:12 PM] 	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
[08/12/2021 21:55:12 PM] 	at java.net.ServerSocket.bind(ServerSocket.java:390)
[08/12/2021 21:55:12 PM] 	at java.net.ServerSocket.bind(ServerSocket.java:344)
[08/12/2021 21:55:12 PM] 	at net.freeutils.httpserver.HTTPServer.createServerSocket(HTTPServer.java:2042)
[08/12/2021 21:55:12 PM] 	at net.freeutils.httpserver.HTTPServer.start(HTTPServer.java:2059)
[08/12/2021 21:55:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.startServer(LoginWithMicrosoftDialog.java:167)
[08/12/2021 21:55:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.<init>(LoginWithMicrosoftDialog.java:114)
[08/12/2021 21:55:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.<init>(LoginWithMicrosoftDialog.java:68)
[08/12/2021 21:55:12 PM] 	at com.atlauncher.gui.tabs.AccountsTab.lambda$new$5(AccountsTab.java:293)
[08/12/2021 21:55:12 PM] 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
[08/12/2021 21:55:12 PM] 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
[08/12/2021 21:55:12 PM] 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
[08/12/2021 21:55:12 PM] 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
[08/12/2021 21:55:12 PM] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
[08/12/2021 21:55:12 PM] 	at java.awt.Component.processMouseEvent(Component.java:6539)
[08/12/2021 21:55:12 PM] 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
[08/12/2021 21:55:12 PM] 	at java.awt.Component.processEvent(Component.java:6304)
[08/12/2021 21:55:12 PM] 	at java.awt.Container.processEvent(Container.java:2239)
[08/12/2021 21:55:12 PM] 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
[08/12/2021 21:55:12 PM] 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
[08/12/2021 21:55:12 PM] 	at java.awt.Component.dispatchEvent(Component.java:4711)
[08/12/2021 21:55:12 PM] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
[08/12/2021 21:55:12 PM] 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
[08/12/2021 21:55:12 PM] 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
[08/12/2021 21:55:12 PM] 	at java.awt.Container.dispatchEventImpl(Container.java:2283)
[08/12/2021 21:55:12 PM] 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
[08/12/2021 21:55:12 PM] 	at java.awt.Component.dispatchEvent(Component.java:4711)
[08/12/2021 21:55:12 PM] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
[08/12/2021 21:55:12 PM] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[08/12/2021 21:55:12 PM] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[08/12/2021 21:55:12 PM] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[08/12/2021 21:55:12 PM] 	at java.security.AccessController.doPrivileged(Native Method)
[08/12/2021 21:55:12 PM] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
[08/12/2021 21:55:12 PM] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
[08/12/2021 21:55:12 PM] 	at java.awt.EventQueue$4.run(EventQueue.java:733)
[08/12/2021 21:55:12 PM] 	at java.awt.EventQueue$4.run(EventQueue.java:731)
[08/12/2021 21:55:12 PM] 	at java.security.AccessController.doPrivileged(Native Method)
[08/12/2021 21:55:12 PM] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
[08/12/2021 21:55:12 PM] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
[08/12/2021 21:55:12 PM] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
[08/12/2021 21:55:12 PM] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[08/12/2021 21:55:12 PM] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[08/12/2021 21:55:12 PM] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[08/12/2021 21:55:12 PM] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[08/12/2021 21:55:12 PM] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by RyanTheAllmighty** [comment]
Superseded by #755
