### ISSUE TITLE
Mod updating hangs on modrinth

### ISSUE THREAD

**Issue by mtb-xt** [ATLauncher/ATLauncher#552]
**Describe the bug**
It started a couple days ago, but now when trying to update mods hangs with the following in the logs:

```
[13/02/2022 12:54:34 PM] SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
[13/02/2022 12:54:34 PM] SLF4J: Defaulting to no-operation MDCAdapter implementation.
[13/02/2022 12:54:34 PM] SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[13/02/2022 12:54:34 PM] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 5798 path $.moderator_message
[13/02/2022 12:54:34 PM] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
[13/02/2022 12:54:34 PM] 	at com.google.gson.Gson.fromJson(Gson.java:932)
[13/02/2022 12:54:34 PM] 	at com.google.gson.Gson.fromJson(Gson.java:870)
[13/02/2022 12:54:34 PM] 	at com.atlauncher.network.Download.asClassWithThrow(Download.java:132)
[13/02/2022 12:54:34 PM] 	at com.atlauncher.network.Download.asClass(Download.java:137)
[13/02/2022 12:54:34 PM] 	at com.atlauncher.network.Download.asClass(Download.java:151)
[13/02/2022 12:54:34 PM] 	at com.atlauncher.utils.ModrinthApi.getProject(ModrinthApi.java:107)
[13/02/2022 12:54:34 PM] 	at com.atlauncher.data.DisableableMod.lambda$checkForUpdate$11(DisableableMod.java:399)
[13/02/2022 12:54:34 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[13/02/2022 12:54:34 PM] Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 5798 path $.moderator_message
[13/02/2022 12:54:34 PM] 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
[13/02/2022 12:54:34 PM] 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:405)
[13/02/2022 12:54:34 PM] 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:393)
[13/02/2022 12:54:34 PM] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
[13/02/2022 12:54:34 PM] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
[13/02/2022 12:54:34 PM] 	... 8 more
[13/02/2022 12:54:34 PM] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 5798 path $.moderator_message
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at com.atlauncher.network.Download.asClassWithThrow(Download.java:132)
	at com.atlauncher.network.Download.asClass(Download.java:137)
	at com.atlauncher.network.Download.asClass(Download.java:151)
	at com.atlauncher.utils.ModrinthApi.getProject(ModrinthApi.java:107)
	at com.atlauncher.data.DisableableMod.lambda$checkForUpdate$11(DisableableMod.java:399)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 5798 path $.moderator_message
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:405)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:393)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 8 more

```

And the 'checking for update' progress bar will wait indefinitely. You can skip this one update by pressing X in the corner of progress bar and some times it will go and update the next mod in the list, but sometimes it happens with the next one.

**To Reproduce**

1. Go to 'Edit Mods' of an Instance where you have added mods yourself (not a modpack, or a modpack with custom added mods)
2. Click on 'Check for updates'
3. Some times it will hang, other times it will work. Is modrinth rate limiting us or something?

**Expected behavior**
Mods would update properly. Maybe, a timeout or a retry mechanism is needed?

**Logs**
Logs posted above

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Arch Linux, running Cinnamon desktop
- Java Version: java-17-openjdk

**Comment by RyanTheAllmighty** [comment]
Can you click "Open Folder" on the instance, then take the `instance.json` file in there and upload it to say https://paste.ee and share the link here.

**Comment by RyanTheAllmighty** [comment]
Yeah looks like one of the fields in the API has changed or more than likely I didn't have an example of it at the time it was implemented, so it's failing on that. I'll push out a fix shortly.
