### ISSUE TITLE
Java version checker seems confused, showing both message boxes.

### ISSUE THREAD

**Issue by Targren** [ATLauncher/ATLauncher#642]
**Describe the bug**
Launcher version 3.4.19.3 (Auto-updated 2022-08-04)

Java version checking seems a little off. Global settings are set to default to Java 16, so trying to open a 1.12.2 pack without adjusting the settings shows the Java 8 warning, as expected, but after closing the Java 8 warning window, it shows me the Java 16+ warning, too.   

When I open the pack settings, without changing anything, the java version Dropdown selector is pointing to Java 8, but the File path select box is pointing at Java 16. 

**To Reproduce**

1. Set global default Java to Java 16. 
2. Install a 1.12.2 pack (I reproduced with "Stoneblock" from Curseforge")
3. Hit "Play" without updating settings. 
4. Open "Settings" for the Instance.  

**Expected behavior**

Only show the Java 8 error.

**Logs**
[2022-08-05 15:38:21 PM]  - \MobGrindingUtils-0.3.13.jar
[2022-08-05 15:38:21 PM]  - \rftools-1.12-7.73.jar
[2022-08-05 15:38:21 PM] Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
[2022-08-05 15:38:21 PM] 	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
[2022-08-05 15:38:21 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[2022-08-05 15:38:21 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Win10
- Java Version: 
    - Eclipse Temurin JDK w/Hotspot 8u332-b09 (x64)
    - Eclipse Temurin JDK w/Hotspot 16.0.2+7 (x64)

Global Settings 
![GlobalSettings](https://user-images.githubusercontent.com/11566412/183149349-eb058745-2591-49fa-bbb1-3c2240cf07a9.PNG)

Instance Settings
![PackSettings_NoChange](https://user-images.githubusercontent.com/11566412/183149351-3f9aa62d-43be-4d2e-a2d3-6367a5f63537.PNG)

**Comment by RyanTheAllmighty** [comment]
Just to note, the top dropdown is just a selector to auto fill in the bottom box. Only the bottom box is used regardless of what the top one says.

Should probably also fix up that confusion by at least adding the custom path you have in the bottom box into the top box so they sync up and don't cause any confusion, as I've definitely seen some confusion around this in the past

**Comment by Targren** [comment]
I thought that was probably the case, but I figured I'd mention it in case it was related. Looking at the commit, I see it wasn't. 😁
