### ISSUE TITLE
Native Wayland 

### ISSUE THREAD

**Issue by Doomsdayrs** [ATLauncher/ATLauncher#658]
**Is your feature request related to a problem? Please describe.**

ATLauncher currently uses the legacy x11 window system to operate.

**Describe the solution you'd like**

Implementation of wayland backend, so the launcher works natively on wayland.

**Additional context**

It seems that JavaFX has wayland support, so migration to that might help. But requires substantial rewriting.
Java swing does not have wayland support, and likely never will

**Comment by Doomsdayrs** [comment]
btw, this can be put as low priority

**Comment by XDream8** [comment]
I think this is a very important thing

**Comment by RyanTheAllmighty** [comment]
> I think this is a very important thing

@XDream8 Why is it? Can you explain why it's needed and what issues it causes not having it to help me understand why it's important.

**Comment by XDream8** [comment]
> 

Fist of all ATLauncher does not launch if you are using wayland without XWayland(**pure wayland**).

And since there is a lot of users that use pure wayland, I think that this is a huge disadvantage and it forces us to use other launchers

**Comment by RyanTheAllmighty** [comment]
Looking in Discord there's about 5 people who have mentioned it, and all have worked around it by launching with a command line argument as listed in https://github.com/ATLauncher/ATLauncher/issues/373

A workaround isn't ideal, but I have yet to see many people come and report the issue, so it's not something seen as too important given the apparent complexity of fixing, vs pointing to a workaround for the few that do come in.

That being said, if you can provide information about your operating system that can be used to verify and test on, it will help to fix it, as at the moment I have no idea and no information on what OS, DE, WM and software is needed to reproduce the issue.

**Comment by Doomsdayrs** [comment]
@XDream8 While I know you might be upset with me marking this as low priority, the reality is that unlike other development environments, ATLauncher is based on GUI toolkits nearly a decade + old.

**Comment by XDream8** [comment]
Tested OS: Void and Kiss linux
Window Manager: sway
XWayland: Disabled

# things that must be noted
Actually that workaround only works if you are using wayland with XWayland support.

if you turn XWayland support off you get this error(same results with both void and kiss linux):
```sh
$ java -jar ATLauncher.jar 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
	at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
	at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1695)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
	at com.atlauncher.managers.DialogManager.show(DialogManager.java:189)
	at com.atlauncher.App.checkInstalledCorrectly(App.java:490)
	at com.atlauncher.App.main(App.java:268)
```

**Comment by Doomsdayrs** [comment]
@XDream8 I do not think I mentioned this here, but currently Java itself does not even have wayland support in it's code base. So this will likely never occur till Java does.

**Comment by ellet0** [comment]
> @XDream8 I do not think I mentioned this here, but currently Java itself does not even have wayland support in it's code base. So this will likely never occur till Java does.

We might get Wayland support in future versions of Java

Related:
- [Jetbrains Wayland support](https://blog.jetbrains.com/platform/2023/08/wayland-support/)
- [Recreating Java Swing for Wayland](https://dev.to/phlash/swingland-recreating-java-swing-for-wayland-2ah6)

**Comment by daedaevibin** [comment]
ATLauncher is not launching using XWayland by default, nor will it connect to an existing `xwayland-satellite` server.

Note: Using `atlauncher-bin`

---

May be related: 

ATLauncher screens, excluding the main logo, remain completely empty, grey, and therefore non-functional.


<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/5b124bad-828b-4ece-8662-f91847071f9a" />


---

Update:
This manual run did work for me, command is as follows:
```fish
.local/share/atlauncher via  v21.0.12 
❯ DISPLAY=:0 _JAVA_AWT_WM_NONREPARENTING=1 java -jar ATLauncher.jar --install-method=aur-bin --no-launcher-update
```

**Comment by Doomsdayrs** [comment]
@daedaevibin If you use the flatpak version of ATLauncher, does this issue still occur?

**Comment by daedaevibin** [comment]
> [@daedaevibin](https://github.com/daedaevibin) If you use the flatpak version of ATLauncher, does this issue still occur?

I only haven't used the flatpak version because it was considerably slower in the past, but I will give it a test and update this comment!

---

Status: `Finished!` 

@Doomsdayrs It does not happen with the flatpak version, so that is safe.
