### ISSUE TITLE
Installation of FTB StoneBlock 3 fails

### ISSUE THREAD

**Issue by quat1024** [ATLauncher/ATLauncher#660]
**Describe the bug**

The *just*-released (like, minutes ago) [FTB StoneBlock 3](https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3) fails to install. The "Generating Pack Version from modpacks.ch" window opens for a few seconds, then changes to an "FTB StoneBlock 3 1.0.0 wasn't installed." dialog.

**To Reproduce**
1. select `Packs` -> `FTB` -> sort by Recently Updated
2. press New Instance on FTB StoneBlock 3
3. leave the default name and version
4. :boom: 

**Logs**
```
[01/11/2022 15:42:58 PM] Organising filesystem
[01/11/2022 15:42:58 PM] ATLauncher Version: 3.4.20.2
[01/11/2022 15:42:58 PM] App Arguments: []
[01/11/2022 15:42:58 PM] JVM Arguments: []
[01/11/2022 15:42:58 PM] Java Version: Java 17 (17.0.4.1)
[01/11/2022 15:42:58 PM] Java Path: C:\Users\quat\scoop\apps\temurin17-jdk\current
[01/11/2022 15:42:58 PM] 64 Bit Java: true
[01/11/2022 15:42:58 PM] RAM Available: 24459MB
[01/11/2022 15:42:58 PM] Launcher Directory: **USERSDIR**
[01/11/2022 15:42:59 PM] GPU: Intel(R) HD Graphics 4000 (Intel Corporation (0x8086)) DriverVersion=10.18.10.4252 2112MB VRAM
[01/11/2022 15:42:59 PM] GPU: NVIDIA GeForce GTX 1650 SUPER (NVIDIA (0x10de)) DriverVersion=30.0.15.1215 4095MB VRAM
[01/11/2022 15:42:59 PM] CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz 4 cores/4 threads
[01/11/2022 15:42:59 PM] Operating System: Windows (10 build 19043)
[01/11/2022 15:42:59 PM] Bitness: 64
[01/11/2022 15:42:59 PM] Uptime: 601717
[01/11/2022 15:42:59 PM] Manufacturer: Microsoft
[01/11/2022 15:42:59 PM] Showing splash screen and loading everything
[01/11/2022 15:42:59 PM] Checking for updated files!
[01/11/2022 15:43:00 PM] Finished downloading updated files!
[01/11/2022 15:43:00 PM] Checking for updates to modpacks.ch instances
[01/11/2022 15:43:00 PM] Launcher finished loading everything
[01/11/2022 15:43:01 PM] Launcher opening
[01/11/2022 15:43:01 PM] Made By Bob*
[01/11/2022 15:43:01 PM] *(Not Actually)
[01/11/2022 15:43:01 PM] Setting up Bottom Bar
[01/11/2022 15:43:01 PM] Finished Setting up Bottom Bar
[01/11/2022 15:43:01 PM] Setting up Tabs
[01/11/2022 15:43:01 PM] Finished Setting up Tabs
[01/11/2022 15:43:01 PM] Showing Launcher
[01/11/2022 15:43:33 PM] Started install of FTB StoneBlock 3 version 1.0.0
[01/11/2022 15:43:34 PM] java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "m.filename" is null
[01/11/2022 15:43:34 PM] 	at com.atlauncher.workers.InstanceInstaller.lambda$null$33(InstanceInstaller.java:981)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[01/11/2022 15:43:34 PM] 	at com.atlauncher.workers.InstanceInstaller.lambda$generatePackVersionFromModpacksCh$35(InstanceInstaller.java:984)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[01/11/2022 15:43:34 PM] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromModpacksCh(InstanceInstaller.java:1001)
[01/11/2022 15:43:34 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:308)
[01/11/2022 15:43:34 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:143)
[01/11/2022 15:43:34 PM] 	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[01/11/2022 15:43:34 PM] 	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01/11/2022 15:43:34 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01/11/2022 15:43:34 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[01/11/2022 15:43:34 PM] java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "m.filename" is null
	at com.atlauncher.workers.InstanceInstaller.lambda$null$33(InstanceInstaller.java:981)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
	at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.atlauncher.workers.InstanceInstaller.lambda$generatePackVersionFromModpacksCh$35(InstanceInstaller.java:984)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromModpacksCh(InstanceInstaller.java:1001)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:308)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:143)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[01/11/2022 15:44:16 PM] Copied Log to clipboard
```

**System information (please complete the following information, or remove if not applicable):**
Should be in the log. I'm using the standalone jar launcher on windows.

**Additional context**
It could maybe be on modpacks.ch's end? Lol

**Comment by quat1024** [comment]
I threw in some debug logging:

added to `ModpacksChPackVersionManifestMod` ->
```diff
+    @Override
+    public String toString() {
+        return String.format("ModpacksChPackVersionManifestMod{fileId=%d, name='%s', synopsis='%s', curseSlug='%s', curseProject=%d, curseFile=%d, stored=%d, filename='%s'}", fileId, name, synopsis, curseSlug, curseProject, curseFile, stored, filename);
+    }
```

added to `InstanceInstaller` ->
```java
Optional<ModpacksChPackVersionManifestMod> modInfo = modsManifest == null ? Optional.empty()
        : modsManifest.mods.parallelStream()
                .filter(m -> {
                    if(m.filename == null) {
                        LogManager.error("NULL FILENAME");
                        LogManager.error("Problematic ModpacksChPackVersionManifestMod: " + m.toString());
                        LogManager.error("The installation process will probably explode now");
                    }

                    return m.filename.equalsIgnoreCase(file.name)
                            || m.filename.equalsIgnoreCase(file.name.replace("_", ""))
                            || m.filename.replace("_", " ").equalsIgnoreCase(file.name);
                })
                .findFirst();
```
and got:
```console
[01/11/2022 16:49:07 PM] NULL FILENAME
[01/11/2022 16:49:07 PM] Problematic ModpacksChPackVersionManifestMod: ModpacksChPackVersionManifestMod{fileId=-1, name='It's Raining Ores Mod', synopsis='ffyyggfdff', curseSlug='its-raining-ores-mod', curseProject=79153, curseFile=788266, stored=1667330847, filename='null'}
[01/11/2022 16:49:07 PM] The installation process will probably explode now
```
The `curseProject` and `curseFile` correspond to the following item in [Stoneblock 3's modpack manifest](https://api.modpacks.ch/public/modpack/100/2275):
```json5
        {
//...
            "id": 311380,
            "name": "Measurements-1.18-1.2.jar",
            "type": "mod",
            "updated": 1667243242,
            "curseforge": {
                "project": 79153,
                "file": 788266
            }
        },
```
...but this is a mod called "Measurements", not "It's Raining Ores Mod"  (I can [barely find evidence of this mod even existing](https://www.modpackindex.com/mod/15627/its-raining-ores-mod) lol).

I'm not sure why this mod is getting misidentified as another mod.

**Comment by quat1024** [comment]
Frightening! There's actually 22 instances of
```json
            "curseforge": {
                "project": 79153,
                "file": 788266
            }
```
in the modpack manifest. Modpacks.ch is really doing something fucky

**Comment by quat1024** [comment]
I don't think this is an ATLauncher issue, modpacks.ch is sending bad data.

**Comment by RyanTheAllmighty** [comment]
Welcome to the world of modpacks.ch APIs. They've actively and seemingly intentionally caused issues for third parties in the past when slowpoke went around and told consumers to stop using it completely.

This is something we need to workaround most likely as we have done in the past, to get around their issues and changes, but I'll need to have a closer look, so I'll reopen for now

**Comment by RyanTheAllmighty** [comment]
@quat1024 we also use the https://api.modpacks.ch/public/modpack/100/2275/mods endpoint to get more information about the mods in the pack. That endpoint we use to get mainly the curse forge IDs, as after they removed urls, not all curse IDs were in the main manifest, but we're only in this second /mods endpoint.

Not sure if that endpoint also has the same bad data issue, as I believe we do filename matching between that data and the main manifest to get missing IDs, but if it's in the main manifest as incorrect, we won't know that.

**Comment by quat1024** [comment]
It looks like FTB's own website is kinda affected too lol (only 14 copies instead of 22)
![image](https://user-images.githubusercontent.com/2068021/199349634-d8465a4f-13f5-4887-b27e-77d50edc9f6c.png)

**Comment by RyanTheAllmighty** [comment]
Yeah that /mods endpoint only seems to have 14 copies of that mod, so I imagine that's what they use as source for their website maybe

**Comment by quat1024** [comment]
was [pointed out](https://twitter.com/yourcompanionAI/status/1587564655584616448) that using the curse API to download this Raining Ores Mod file works, but the file is zero bytes 👀

anecdotally i remember that empty files submitted to curse get rejected with a "file is a duplicate of \[[random bukkit plugin that also uploaded a zero-byte file once](https://www.curseforge.com/minecraft/bukkit-plugins/autobanplus)\]" message. i guess that's why it happens

**Comment by RyanTheAllmighty** [comment]
It's a complete mystery to me how this works for FTB launcher. Last I saw using a network monitor tool like fiddler, they were using the same API routes, so unless that's changed, I'm not sure how their own launcher is working

**Comment by hvdklauw** [comment]
My guess would be that they don't download from curse, but from their own cached versions. Which would mean their caching system is wrong too

**Comment by hvdklauw** [comment]
Just a fyi: prismlaumcher just downloaded the pack without issue, before it would install but then mods and confgs where missing. But now it at least runs

**Comment by DioEgizio** [comment]
> It's a complete mystery to me how this works for FTB launcher. Last I saw using a network monitor tool like fiddler, they were using the same API routes, so unless that's changed, I'm not sure how their own launcher is working

I think they do filtering based on user agent

**Comment by RyanTheAllmighty** [comment]
Looks like they've fixed their manifest now, but not their `/mods` endpoint we use which is still busted. Might need to just remove that now as it was just a workaround for issues installing packs with missing curseforge id's, but I'm not sure if they completely fixed that or not.

@jamierocks I believe you may have had a tool at one point which looked for modpacks on modpacks.ch with null or missing CurseForge information? Do you still have that

**Comment by RyanTheAllmighty** [comment]
Worked around this for now, the main issue was the info from `/mods` endpoint, which we used to fix issues with modpacks.ch manifests having null curseforge information was messed up for this particular pack and was trying to download wrong mod ids, so just deprioritised it if the manifest has correct curseforge information.

**Comment by jamierocks** [comment]
>  @jamierocks I believe you may have had a tool at one point which looked for modpacks on modpacks.ch with null or missing CurseForge information? Do you still have that

I have a tool that can dump all modpacks.ch packs. The rest was `grep 'curseforge": null' -r . | uniq -c | sort` :) I've just run the dumper, it appears there aren't any null curseforge objects currently.
