### ISSUE TITLE
Cannot log in to Microsoft account after being told account was offline

### ISSUE THREAD

**Issue by richtoph3r** [ATLauncher/ATLauncher#662]
**Describe the bug**
Attempting to log in with a Microsoft account results in failure.

**To Reproduce**

1. Account was considered offline and couldn't log in with current login details
2. Remove account from launcher
3. Attempt to login with Microsoft
4. Select Microsoft account associated with Minecraft account (see attached screenshot)

**Expected behavior**
1. Click "Login with Microsoft"
2. Authorize ATlauncher to access Microsoft/Xbox live
3. Account is added to ATlauncher

**Logs**
[11/07/2022 21:50:13 PM] Console Cleared
[11/07/2022 21:50:29 PM] com.atlauncher.network.DownloadException: https://api.minecraftservices.com/launcher/login request wasn't successful: Response{protocol=h2, code=504, message=, url=https://api.minecraftservices.com/launcher/login}
[11/07/2022 21:50:29 PM] 	at com.atlauncher.network.Download.execute(Download.java:321)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.network.Download.asClassWithThrow(Download.java:136)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.network.Download.asClass(Download.java:143)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.network.Download.asClass(Download.java:157)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.utils.MicrosoftAuthAPI.loginToMinecraft(MicrosoftAuthAPI.java:119)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireMinecraftToken(LoginWithMicrosoftDialog.java:250)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXsts(LoginWithMicrosoftDialog.java:241)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXBLToken(LoginWithMicrosoftDialog.java:207)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:201)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)
[11/07/2022 21:50:29 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[11/07/2022 21:50:29 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[11/07/2022 21:50:29 PM] 	at java.base/java.lang.Thread.run(Thread.java:834)
[11/07/2022 21:50:29 PM] com.atlauncher.network.DownloadException: https://api.minecraftservices.com/launcher/login request wasn't successful: Response{protocol=h2, code=504, message=, url=https://api.minecraftservices.com/launcher/login}

	at com.atlauncher.network.Download.execute(Download.java:321)

	at com.atlauncher.network.Download.asClassWithThrow(Download.java:136)

	at com.atlauncher.network.Download.asClass(Download.java:143)

	at com.atlauncher.network.Download.asClass(Download.java:157)

	at com.atlauncher.utils.MicrosoftAuthAPI.loginToMinecraft(MicrosoftAuthAPI.java:119)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireMinecraftToken(LoginWithMicrosoftDialog.java:250)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXsts(LoginWithMicrosoftDialog.java:241)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXBLToken(LoginWithMicrosoftDialog.java:207)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:201)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)

	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)

	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)

	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)

	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)

	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)

[11/07/2022 21:50:29 PM] Error acquiring accessToken
[11/07/2022 21:50:29 PM] java.lang.Exception: Failed to login to Minecraft
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireMinecraftToken(LoginWithMicrosoftDialog.java:253)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXsts(LoginWithMicrosoftDialog.java:241)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXBLToken(LoginWithMicrosoftDialog.java:207)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:201)
[11/07/2022 21:50:29 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)
[11/07/2022 21:50:29 PM] 	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)
[11/07/2022 21:50:29 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[11/07/2022 21:50:29 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[11/07/2022 21:50:29 PM] 	at java.base/java.lang.Thread.run(Thread.java:834)
[11/07/2022 21:50:29 PM] java.lang.Exception: Failed to login to Minecraft

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireMinecraftToken(LoginWithMicrosoftDialog.java:253)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXsts(LoginWithMicrosoftDialog.java:241)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXBLToken(LoginWithMicrosoftDialog.java:207)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:201)

	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)

	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)

	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)

	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)

	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)

	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)

**Screenshots**

![Screenshot 2022-11-07 220300](https://user-images.githubusercontent.com/77136485/200488631-fd8168fe-d777-45b0-b075-6334ddb15467.png)

**System information (please complete the following information, or remove if not applicable):**

Operating System
			Windows 10 Pro 64-bit
		CPU
			Intel Core i7 7700K @ 4.20GHz	32 °C
			Kaby Lake 14nm Technology
		RAM
			32.0GB Dual-Channel Unknown @ 1600MHz (16-18-18-36)
		Motherboard
			ASUSTeK COMPUTER INC. MAXIMUS IX HERO (LGA1151)	27 °C
		Graphics
			LG ULTRAGEAR (2560x1440@144Hz)
			S32F351 (1920x1080@60Hz)
			3071MB NVIDIA GeForce GTX 1080 Ti (PNY)	40 °C

Java Version 8 update 351

**Additional Information**

I still have access to my Microsoft and Minecraft accounts. I revoked and then reauthorized ATlauncher's permission to access my account while troubleshooting.

**Comment by RyanTheAllmighty** [comment]
There are login issues currently, try again later. If you have issues please use Discord
