### ISSUE TITLE
xrandr must be installed to launch Minecraft

### ISSUE THREAD

**Issue by UniversalSuperBox** [ATLauncher/ATLauncher#690]
I'm using ATLauncher on Fedora 37, and was receiving the following error when launching a Minecraft 1.12.2 pack:

```
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 27 more
```

This issue was caused by the `xrandr` command being unavailable to Java. Installing the `xrandr` package fixed the problem.

Adding that package as a requirement to the specfile should make it easier for others to use ATLauncher in the future

**Comment by Doomsdayrs** [comment]
Did you use the version on the software store?

**Comment by UniversalSuperBox** [comment]
I downloaded the ATLauncher RPM from https://atlauncher.com/downloads
