### ISSUE TITLE
Unresponsive Launch

### ISSUE THREAD

**Issue by Siarune** [ATLauncher/ATLauncher#712]
ATLauncher silently fails to launch from any menu and when run from the command line, it outputs:

```
java.lang.RuntimeException: Failed to invoke public com.atlauncher.data.Settings() with no args
at com.google.gson.internal.ConstructorConstructor$4.construct(ConstructorConstructor.java:149)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:211)
at com.google.gson.Gson.fromJson(Gson.java:991)
at com.google.gson.Gson.fromJson(Gson.java:929)
at com.atlauncher.App.loadSettings(App.java:688)
at com.atlauncher.App.main(App.java:281)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
at java.desktop/java.awt.Dimension.<clinit>(Dimension.java:88)
at com.atlauncher.data.Settings.<init>(Settings.java:57)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at com.google.gson.internal.ConstructorConstructor$4.construct(ConstructorConstructor.java:140)
... 5 more
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Dimension
at com.atlauncher.data.Settings.<init>(Settings.java:57)
at com.atlauncher.App.loadSettings(App.java:691)
at com.atlauncher.App.main(App.java:281)
```

Run on:
arch linux (garuda)
ATLauncher `chaotic-aur/atlauncher-bin 3.4.24.1-1`
kernel `linux-zen 6.1.7.zen1-1`
java `jdk-openjdk 19.0.2.u7-2`

A full reinstall of `aur/atlauncher 3.4.24.1-1` has no effect but Gradle has some suspicious warnings
```
Starting a Gradle Daemon (subsequent builds will be faster)
ATLauncher has been built. Distribution files are located in the dist directory.

> Task :generateMainServiceApolloSources
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.9.2
ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.9.2
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.9.2
ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.9.2

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileTestJava
Note: /home/sia/.cache/paru/clone/atlauncher/src/ATLauncher-3.4.24.1/src/test/java/ui/AbstractUiTest.java usesor overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :downloadNewerUniversalJavaApplicationStub
Download https://raw.githubusercontent.com/tofi86/universalJavaApplicationStub/2dbbf92b35e61194266c985c8bc6b411053a1b4a/src/universalJavaApplicationStub

> Task :createAppZip
Execution optimizations have been disabled for task ':createAppZip' to ensure correctness due to the followingreasons:
- Gradle detected a problem with the following location: '/home/sia/.cache/paru/clone/atlauncher/src/ATLauncher-3.4.24.1/build/macApp'. Reason: Task ':createAppZip' uses this output of task ':downloadNewerUniversalJavaApplicationStub' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6-milestone-1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :startScripts
Execution optimizations have been disabled for task ':startScripts' to ensure correctness due to the followingreasons:
- Gradle detected a problem with the following location: '/home/sia/.cache/paru/clone/atlauncher/src/ATLauncher-3.4.24.1/build/libs/ATLauncher-3.4.24.1.jar'. Reason: Task ':startScripts' uses this output of task ':shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6-milestone-1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :distTar
Execution optimizations have been disabled for task ':distTar' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/home/sia/.cache/paru/clone/atlauncher/src/ATLauncher-3.4.24.1/build/libs/ATLauncher-3.4.24.1.jar'. Reason: Task ':distTar' uses this output of task ':shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6-milestone-1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :distZip
Execution optimizations have been disabled for task ':distZip' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/home/sia/.cache/paru/clone/atlauncher/src/ATLauncher-3.4.24.1/build/libs/ATLauncher-3.4.24.1.jar'. Reason: Task ':distZip' uses this output of task ':shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6-milestone-1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :createExe
Execution optimizations have been disabled for task ':createExe' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/home/sia/.cache/paru/clone/atlauncher/src/ATLauncher-3.4.24.1/build/libs/ATLauncher-3.4.24.1.jar'. Reason: Task ':createExe' uses this output of task ':shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6-milestone-1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :createMacApp
Execution optimizations have been disabled for task ':createMacApp' to ensure correctness due to the followingreasons:
- Gradle detected a problem with the following location: '/home/sia/.cache/paru/clone/atlauncher/src/ATLauncher-3.4.24.1/build/macApp'. Reason: Task ':createMacApp' uses this output of task ':downloadNewerUniversalJavaApplicationStub' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6-milestone-1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :legacy-launch:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6-milestone-1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 6 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
```

I hope I was explicit enough with the details, but please don't hesitate to ask me. I don't know enough about Java to really troubleshoot this on my own.

**Comment by RyanTheAllmighty** [comment]
`java.lang.NoClassDefFoundError: Could not initialize class java.awt.Dimension`

Makes me think you're using a headless version of Java. Confirm with your package manager and `java -version` to make sure it's not a headless Java

**Comment by Siarune** [comment]
Here's the output of `java -version`, which doesn't appear to be headless
I've since switched the default with `archlinux-java` and ATLauncher is running again
```
Available Java environments:
java-11-openjdk (default)
java-17-openjdk
java-19-openjdk

openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10)
OpenJDK 64-Bit Server VM (build 11.0.18+10, mixed mode)
```

to

```
Available Java environments:
java-11-openjdk
java-17-openjdk
java-19-openjdk (default)

openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7)
OpenJDK 64-Bit Server VM (build 19.0.2+7, mixed mode)
```

**Comment by RyanTheAllmighty** [comment]
Yeah looking at Google it's an issue with the system/Java not having some AWT library or in headless mode.
