### ISSUE TITLE
Any "Open Folder" buttons do not work

### ISSUE THREAD

**Issue by Blackilykat** [ATLauncher/ATLauncher#713]
**Describe the bug**
Whenever I try to click any of the open folder buttons in the launcher they don't do anything except throw an error at console.

**To Reproduce**
1.  Open the launcher
2. Click on "Open Folder"

**Expected behavior**
A new File Explorer window pops up on the client's folder.

**Logs**
I'm only posting the error to not make it too long, let me know if you need the whole thing
```
[21/01/2023 13:33:41 PM] Error opening file explorer!
[21/01/2023 13:33:41 PM] java.io.IOException: Failed to show URI:file:**USERSDIR**/
[21/01/2023 13:33:41 PM] 	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
[21/01/2023 13:33:41 PM] 	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
[21/01/2023 13:33:41 PM] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:203)
[21/01/2023 13:33:41 PM] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:185)
[21/01/2023 13:33:41 PM] 	at com.atlauncher.gui.components.LauncherBottomBar.lambda$setupListeners$1(LauncherBottomBar.java:95)
[21/01/2023 13:33:41 PM] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[21/01/2023 13:33:41 PM] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[21/01/2023 13:33:41 PM] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[21/01/2023 13:33:41 PM] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[21/01/2023 13:33:41 PM] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
[21/01/2023 13:33:41 PM] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[21/01/2023 13:33:41 PM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[21/01/2023 13:33:41 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[21/01/2023 13:33:41 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
[21/01/2023 13:33:41 PM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[21/01/2023 13:33:41 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[21/01/2023 13:33:41 PM] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[21/01/2023 13:33:41 PM] java.io.IOException: Failed to show URI:file:**USERSDIR**/
	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:203)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:185)
	at com.atlauncher.gui.components.LauncherBottomBar.lambda$setupListeners$1(LauncherBottomBar.java:95)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Screenshots**
![2023-01-21-13-41-05](https://user-images.githubusercontent.com/66535696/213867348-78040868-5873-472d-a038-03688cf94701.gif)

**System information (please complete the following information, or remove if not applicable):**

- Manjaro linux | KDE Plasma Version 5.26.4 | KDE Frameworks version 5.101.0 | Qt Version: 5.15.7 | Kernel Version: 6.1.1-1-MANJARO (64-bit) | Graphics Platform: X11
- openjdk version "17.0.5" 2022-10-18 | OpenJDK Runtime Environment (build 17.0.5+1) | OpenJDK 64-Bit Server VM (build 17.0.5+1, mixed mode)

**Comment by RyanTheAllmighty** [comment]
Yeah looks like Java has no idea how to open a file given your DE. Might need to rearrange the order of the if statements at https://github.com/ATLauncher/ATLauncher/blob/0e99a68d54c5b1ed83ffc675752c419944d573d6/src/main/java/com/atlauncher/utils/OS.java#L204 and expand it for Linux a bit more

**Comment by RyanTheAllmighty** [comment]
Transfer from #736 

---

From @kyngs

---



**Describe the bug**
When I try to press the open folder button, nothing happens. Looking at the terminal output, I can spot this error:
/usr/bin/dolphin: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
When I press the open website button, nothing happens. Also, nothing appears in the logs.
btw, I do not have apparmor installed

**To Reproduce**
Press the open folder or open website button on some instance in the launcher.

**Expected behavior**
Dolphin/Firefox opens.

**Logs**
Logs from terminal:  https://pastebin.com/2KYZHWKA
ATLauncher logs: https://paste.atlauncher.com/view/3bf494e0-7ac9-480e-8c51-b76125857d58

**Screenshots**
Not applicable.

**System information (please complete the following information, or remove if not applicable):**

- OS: Arch Linux x86_64 6.2.7-zen1-1-zen
- DE: KDE Plasma 5.27.3
- Java Version: openjdk 17.0.6 2023-01-17 (using java 8 does not help)
- Drivers: Nvidia Proprietary (525.89.02)
- File Manager: Dolphin
- Web Browser: Firefox

**Additional context**
This may be my system setup issue, tell me what other system info you need.

**Comment by kyngs** [comment]
Interestingly, the buttons work when I clone the repo, open it in IJ, and use the `Launch` run configuration.

**Comment by kyngs** [comment]
@Blackilykat I suspect you were also using Lutris? If yes, I found a solution. Right-click on ATLauncher -> Configure -> System options -> Disable Lutris Runtime.

**Comment by Blackilykat** [comment]
> @Blackilykat I suspect you were also using Lutris? If yes, I found a solution. Right-click on ATLauncher -> Configure -> System options -> Disable Lutris Runtime.

I was not using Lutris but it started working again at some point, I don't remember what could have changed though, except the window manager which was while I had the issue and might have been xfce or i3 when it worked again. I forgot when that was but people were still having the issue so I kept it open.

**Comment by kyngs** [comment]
> > @Blackilykat I suspect you were also using Lutris? If yes, I found a solution. Right-click on ATLauncher -> Configure -> System options -> Disable Lutris Runtime.
> 
> I was not using Lutris but it started working again at some point, I don't remember what could have changed though, except the window manager which was while I had the issue and might have been xfce or i3 when it worked again. I forgot when that was but people were still having the issue so I kept it open.

Hm, in my case nothing even appeared in the logs. Maybe we were experiencing two different bugs with the same symptoms.

**Comment by homemmakako** [comment]
Having the same issue on Manjaro XFCE Linux 6.6

By launching ATLauncher through the terminal (`atlauncher --debug`) I get the following errors (these show on the terminal, not on ATLauncher's console):

```
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
```

Launcher console shows no errors or other logs even in debug mode.

**Comment by kyngs** [comment]
Wiat what, since when atlauncher uses electron?

**Comment by RyanTheAllmighty** [comment]
We don't use electron, those console lines are unrelated to the launcher directly

**Comment by Blackilykat** [comment]
Encountered this again after coming back to atlauncher and installing it through flatpak, I am now on Arch Linux.
Installing it trough the [atlauncher-bin](https://aur.archlinux.org/packages/atlauncher-bin) AUR package fixes the issue, so I think the problem is in the flatpak.

**Comment by ClearAspect** [comment]
I'm experiencing the exact same issue and receiving the same error displayed in the initial post 
OS: Arch Linux
DE: Hyprland
File Manager: Gnome Files (Nautilus)

**Comment by flurbudurbur** [comment]
I also have this issue.
Install method: AUR/atlauncher (not bin/git)
OS: Garuda
KDE Plasma 6.0
File Manager: Dolphin

**Comment by kyngs** [comment]
Can you verify whether installing atlauncher-bin helps?

**Comment by flurbudurbur** [comment]
alright I just did and no change unfortunately. Rebooted just to be sure.

**Comment by mardevour** [comment]
I am also having this issue on Arch and Endeavour.

    Install method: Flatpak
    OS: Arch Linux x86_64 and EndeavourOS x86_64
    DE: i3wm 4.23-4
    File Manager: Thunar
    Web Browser: Firefox

`[22/09/2024 16:55:33 p. m.] Error opening file explorer!
[22/09/2024 16:55:33 p. m.] java.io.IOException: Failed to show URI:file:**USERSDIR**/instances/amigos/
[22/09/2024 16:55:33 p. m.] 	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
[22/09/2024 16:55:33 p. m.] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:207)
[22/09/2024 16:55:33 p. m.] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:189)
[22/09/2024 16:55:33 p. m.] 	at com.atlauncher.gui.card.InstanceCard$1.mousePressed(InstanceCard.java:87)
[22/09/2024 16:55:33 p. m.] 	at com.atlauncher.gui.components.DropDownButton$1.mousePressed(DropDownButton.java:55)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[22/09/2024 16:55:33 p. m.] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[22/09/2024 16:55:33 p. m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[22/09/2024 16:55:33 p. m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[22/09/2024 16:55:33 p. m.] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[22/09/2024 16:55:33 p. m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[22/09/2024 16:55:33 p. m.] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[22/09/2024 16:55:33 p. m.] java.io.IOException: Failed to show URI:file:**USERSDIR**/instances/amigos/
	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:207)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:189)
	at com.atlauncher.gui.card.InstanceCard$1.mousePressed(InstanceCard.java:87)
	at com.atlauncher.gui.components.DropDownButton$1.mousePressed(DropDownButton.java:55)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by Bissela** [comment]
Install method: Flatpak
OS: EndeavourOS x86_64, Kernel 6.15.4-arch2-1
DE: Cinnamon 6.4.10
File Manager: Nemo
Web Browser: Firefox
"java -version" command output:
openjdk version "24.0.1" 2025-04-15
OpenJDK Runtime Environment (build 24.0.1)
OpenJDK 64-Bit Server VM (build 24.0.1, mixed mode, sharing)

I had the same problem with LXDE desktop, Open Folder and Add Mods -> View didn't open anything.
Then I installed Cinnamon with command "sudo pacman -S cinnamon system-config-printer gnome-keyring blueberry cinnamon-translations"
After that, in Cinnamon everything works and LXDE it also works as expected.
