### ISSUE TITLE
Http related actions are broken in the latest source code

### ISSUE THREAD

**Issue by zeng-github01** [ATLauncher/ATLauncher#742]
**Describe the bug**
All Http related actions are broken in the latest source code, including modpack installation, Vanilla Packs installation, log upload

**To Reproduce**

Execute the corresponding behavior, such as executing ATLauncher's own log upload

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

`] Failed to receive response from paste API
[2023/04/01 10:26:12 上午] java.io.IOException: Server returned HTTP response code: 403 for URL: https://paste.atlauncher.com/api/create
[2023/04/01 10:26:12 上午] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[2023/04/01 10:26:12 上午] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[2023/04/01 10:26:12 上午] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[2023/04/01 10:26:12 上午] 	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:75)
[2023/04/01 10:26:12 上午] 	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:36)
[2023/04/01 10:26:12 上午] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2023/04/01 10:26:12 上午] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2023/04/01 10:26:12 上午] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2023/04/01 10:26:12 上午] 	at java.lang.Thread.run(Unknown Source)
[2023/04/01 10:26:12 上午] java.io.IOException: Server returned HTTP response code: 403 for URL: https://paste.atlauncher.com/api/create
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:75)
	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:36)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Screenshots**

**System information (please complete the following information, or remove if not applicable):**

- OS (including distro/version): Windows 11 22H2 
- Java Version: JRE_361

**Additional context**
It has been tested on 3.4.27.0 and it works normally

**Comment by RyanTheAllmighty** [comment]
Working fine here running from source

**Comment by RyanTheAllmighty** [comment]
403 errors usually mean you got blocked by our firewall. Given the fact the official launcher is working for you, I'd say that's the issue, you may have been flagged and blocked from the api. But without further information on how you're running the launcher, if it's from source via an IDE or through a built jar/exe, I can't confirm that.

**Comment by RedLime** [comment]
Isn't it related to old Java doesn't support letsencrypt certification? I had to similar issue like this before on my project

**Comment by zeng-github01** [comment]
It may be a proxy problem. I am in China, and I cannot upload logs on version 27 without using a proxy, but 403 will occur on version 28. @RyanTheAllmighty I will try another proxy

**Comment by zeng-github01** [comment]
> 403错误通常意味着您被我们的防火墙阻止了。鉴于官方启动器正在为您工作，我想说这就是问题所在，您可能已被标记并阻止使用 API。但是，如果没有关于您如何运行启动器的更多信息，如果它是通过 IDE 或通过构建的 jar/exe 从源代码获取的，我无法确认这一点。

Problem confirmed. When changing the proxy setting of ATLauncher from SOCKS to HTTP, related functions can be performed normally
