### ISSUE TITLE
Error on GraphQL query

### ISSUE THREAD

**Issue by RobertLSnead** [ATLauncher/ATLauncher#745]
OS: Linux Manjaro 22.1.0

I am having GraphQL query errors while trying to install any modpack!
Not sure what to do or what I am doing wrong.
Any help is appreciated.

-See Console Log Below

[04/04/2023 18:36:53 PM] Console Cleared
[04/04/2023 18:37:03 PM] Started install of Techopolis version Techopolis (3.0)
[04/04/2023 18:37:04 PM] Error on GraphQL query
[04/04/2023 18:37:04 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
[04/04/2023 18:37:04 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
[04/04/2023 18:37:04 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
[04/04/2023 18:37:04 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
[04/04/2023 18:37:04 PM] 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[04/04/2023 18:37:04 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[04/04/2023 18:37:04 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[04/04/2023 18:37:04 PM] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[04/04/2023 18:37:04 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
[04/04/2023 18:37:04 PM] java.lang.Exception: Failed to find loader version for 36.2.35
[04/04/2023 18:37:04 PM] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForgeManifest(InstanceInstaller.java:494)
[04/04/2023 18:37:04 PM] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForge(InstanceInstaller.java:794)
[04/04/2023 18:37:04 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:305)
[04/04/2023 18:37:04 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:146)
[04/04/2023 18:37:04 PM] 	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
[04/04/2023 18:37:04 PM] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[04/04/2023 18:37:04 PM] 	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
[04/04/2023 18:37:04 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[04/04/2023 18:37:04 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[04/04/2023 18:37:04 PM] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[04/04/2023 18:37:04 PM] java.lang.Exception: Failed to find loader version for 36.2.35
	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForgeManifest(InstanceInstaller.java:494)
	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForge(InstanceInstaller.java:794)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:305)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:146)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
[04/04/2023 18:37:22 PM] Started install of SkyFactory 4 version SkyFactory 4 - 4.2.4
[04/04/2023 18:37:23 PM] Error on GraphQL query
[04/04/2023 18:37:23 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
[04/04/2023 18:37:23 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
[04/04/2023 18:37:23 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
[04/04/2023 18:37:23 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
[04/04/2023 18:37:23 PM] 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[04/04/2023 18:37:23 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[04/04/2023 18:37:23 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[04/04/2023 18:37:23 PM] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[04/04/2023 18:37:23 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
[04/04/2023 18:37:23 PM] java.lang.Exception: Failed to find loader version for 14.23.5.2860
[04/04/2023 18:37:23 PM] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForgeManifest(InstanceInstaller.java:494)
[04/04/2023 18:37:23 PM] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForge(InstanceInstaller.java:794)
[04/04/2023 18:37:23 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:305)
[04/04/2023 18:37:23 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:146)
[04/04/2023 18:37:23 PM] 	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
[04/04/2023 18:37:23 PM] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[04/04/2023 18:37:23 PM] 	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
[04/04/2023 18:37:23 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[04/04/2023 18:37:23 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[04/04/2023 18:37:23 PM] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[04/04/2023 18:37:23 PM] java.lang.Exception: Failed to find loader version for 14.23.5.2860
	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForgeManifest(InstanceInstaller.java:494)
	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForge(InstanceInstaller.java:794)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:305)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:146)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by Doomsdayrs** [comment]
This is likely due to a block to https://api.atlauncher.com (as I have just experienced this)

I suggest contacting support for this.
