### ISSUE TITLE
UX and logging issues when MS Auth fails

### ISSUE THREAD

**Issue by vadcx** [ATLauncher/ATLauncher#752]
### What happened?

1. Try to launch a modpack
2. Auth expired, prompted to login again by the launcher
3. Go through the auth process in the web browser
4. Agree to sign in with ATLauncher
5. Process fails with NPE, due to receiving HTTP 400 from the server. Message in browser from the local server: "Error logging in. Check console for more information"
6. Asked to login by the launcher, goto 3

---

I have seen ATLauncher#662:

> There are login issues currently with Microsoft, out of our control, try again later. If you continue to have issues in 6-12 hours, please use Discord

I don't know if there currently are issues, regardless of that:

1. The launcher blindly loops the auth process, because the last attempt failed
2. The error is not clearly propagated to the launcher GUI to notify the user
   - Should there be exception stacktraces in console? I don't think so. It should be handled cleanly
3. The DownloadException shows no info about the request itself beyond the URL. This is not helpful esp. for bug reporting :( I tried setting the "Log Level" to FINEST (Settings → Logging) but there is not one bit of additional info.

That's pretty packed, feel free to split it up into feature requests/bug reports.

The exceptions picked from the attached log:

1. `com.atlauncher.network.DownloadException: https://login.live.com/oauth20_token.srf request wasn't successful: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://login.live.com/oauth20_token.srf}`
2. \> `acquireXBLToken(LoginWithMicrosoftDialog.java:205)`

### Operating System

Linux

### Relevant log output

```shell
ATLauncher Version: 3.4.28.1 [9123cdc03237c5c3efa5dd8a1e8dffeaff0f5770]
App Arguments: ["--install-method\u003daur-bin","--no-launcher-update"]
JVM Arguments: ["-Dawt.useSystemAAFontSettings\u003don","-Dswing.aatext\u003dtrue"]
Java Version: Java 11 (11.0.18)
Java Path: /usr/lib/jvm/java-19-openjdk
64 Bit Java: true

---

[2023-04-22 19:46:55 PM] Preparing for launch!
[2023-04-22 19:46:56 PM] Launching pack All the Mods 8 - ATM8 1.0.15 (CurseForge) for Minecraft 1.19.2
[2023-04-22 19:46:56 PM] Logging into Minecraft!
[2023-04-22 19:46:56 PM] Access Token has expired. Attempting to refresh it.
[2023-04-22 19:46:56 PM] Oauth token expired. Attempting to refresh
[2023-04-22 19:46:58 PM] com.atlauncher.network.DownloadException: https://login.live.com/oauth20_token.srf request wasn't successful: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://login.live.com/oauth20_token.srf}
[2023-04-22 19:46:58 PM] 	at com.atlauncher.network.Download.execute(Download.java:323)
[2023-04-22 19:46:58 PM] 	at com.atlauncher.network.Download.asClassWithThrow(Download.java:138)
[2023-04-22 19:46:58 PM] 	at com.atlauncher.network.Download.asClass(Download.java:145)
[2023-04-22 19:46:58 PM] 	at com.atlauncher.utils.MicrosoftAuthAPI.refreshAccessToken(MicrosoftAuthAPI.java:64)
[2023-04-22 19:46:58 PM] 	at com.atlauncher.data.MicrosoftAccount.refreshAccessToken(MicrosoftAccount.java:163)
[2023-04-22 19:46:58 PM] 	at com.atlauncher.data.MicrosoftAccount.refreshAccessToken(MicrosoftAccount.java:156)
[2023-04-22 19:46:58 PM] 	at com.atlauncher.data.MicrosoftAccount.ensureAccessTokenValid(MicrosoftAccount.java:319)
[2023-04-22 19:46:58 PM] 	at com.atlauncher.data.Instance.lambda$null$16(Instance.java:1038)
[2023-04-22 19:46:58 PM] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-22 19:46:58 PM] com.atlauncher.network.DownloadException: https://login.live.com/oauth20_token.srf request wasn't successful: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://login.live.com/oauth20_token.srf}
	at com.atlauncher.network.Download.execute(Download.java:323)
	at com.atlauncher.network.Download.asClassWithThrow(Download.java:138)
	at com.atlauncher.network.Download.asClass(Download.java:145)
	at com.atlauncher.utils.MicrosoftAuthAPI.refreshAccessToken(MicrosoftAuthAPI.java:64)
	at com.atlauncher.data.MicrosoftAccount.refreshAccessToken(MicrosoftAccount.java:163)
	at com.atlauncher.data.MicrosoftAccount.refreshAccessToken(MicrosoftAccount.java:156)
	at com.atlauncher.data.MicrosoftAccount.ensureAccessTokenValid(MicrosoftAccount.java:319)
	at com.atlauncher.data.Instance.lambda$null$16(Instance.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-22 19:46:58 PM] Failed to refresh accessToken
[2023-04-22 19:46:58 PM] Failed to login
[2023-04-22 19:47:16 PM] Copied Log to clipboard

---

Go through the oauth login, "Do you want to login with ATLauncher" -> Yes

---

[2023-04-22 19:49:11 PM] You must login to your account before continuing.
[2023-04-22 19:50:12 PM] com.atlauncher.network.DownloadException: https://login.live.com/oauth20_token.srf request wasn't successful: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://login.live.com/oauth20_token.srf}
[2023-04-22 19:50:12 PM] 	at com.atlauncher.network.Download.execute(Download.java:323)
[2023-04-22 19:50:12 PM] 	at com.atlauncher.network.Download.asClassWithThrow(Download.java:138)
[2023-04-22 19:50:12 PM] 	at com.atlauncher.network.Download.asClass(Download.java:145)
[2023-04-22 19:50:12 PM] 	at com.atlauncher.utils.MicrosoftAuthAPI.tradeCodeForAccessToken(MicrosoftAuthAPI.java:52)
[2023-04-22 19:50:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:199)
[2023-04-22 19:50:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)
[2023-04-22 19:50:12 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-04-22 19:50:12 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-04-22 19:50:12 PM] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-22 19:50:12 PM] com.atlauncher.network.DownloadException: https://login.live.com/oauth20_token.srf request wasn't successful: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://login.live.com/oauth20_token.srf}
	at com.atlauncher.network.Download.execute(Download.java:323)
	at com.atlauncher.network.Download.asClassWithThrow(Download.java:138)
	at com.atlauncher.network.Download.asClass(Download.java:145)
	at com.atlauncher.utils.MicrosoftAuthAPI.tradeCodeForAccessToken(MicrosoftAuthAPI.java:52)
	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:199)
	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)
	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)
	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)
	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)
	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)
	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-22 19:50:12 PM] Error acquiring accessToken
[2023-04-22 19:50:12 PM] java.lang.NullPointerException
[2023-04-22 19:50:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXBLToken(LoginWithMicrosoftDialog.java:205)
[2023-04-22 19:50:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:201)
[2023-04-22 19:50:12 PM] 	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)
[2023-04-22 19:50:12 PM] 	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)
[2023-04-22 19:50:12 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-04-22 19:50:12 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-04-22 19:50:12 PM] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-22 19:50:12 PM] java.lang.NullPointerException
	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireXBLToken(LoginWithMicrosoftDialog.java:205)
	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.acquireAccessToken(LoginWithMicrosoftDialog.java:201)
	at com.atlauncher.gui.dialogs.LoginWithMicrosoftDialog.lambda$startServer$0(LoginWithMicrosoftDialog.java:150)
	at net.freeutils.httpserver.HTTPServer.serve(HTTPServer.java:2268)
	at net.freeutils.httpserver.HTTPServer.handleMethod(HTTPServer.java:2204)
	at net.freeutils.httpserver.HTTPServer.handleTransaction(HTTPServer.java:2145)
	at net.freeutils.httpserver.HTTPServer.handleConnection(HTTPServer.java:2105)
	at net.freeutils.httpserver.HTTPServer$SocketHandlerThread$1.run(HTTPServer.java:1905)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	
---
Failed to login and the process repeats.
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Unfortunately there is no further information other than the status code when this happens. We show error messages when there are known error codes coming from Microsoft, but largely there are none.

The log level in the settings is for forge logging within Minecraft, doesn't affect the launcher.

Not sure there's anything here to fix?

**Comment by vadcx** [comment]
The issue about the lack of debug info from the API still stands

I will simply describe how I managed to unbreak the MS account.

-----

**What:** Unable to login with the Microsoft account / endless verification code loop. Any browser. While I could login in Firefox, I couldn't access the *account settings* through `office.com` (verification loop) - but I could see the inbox etc. With Edge (fresh install): I couldn't login at all.

**Fix:** You need to go through "forgot password" or whatever, reset it then login again. It will work in all browsers now, including OAuth API.

**Probable reason:** I didn't setup an account password during migration, because the website never asked me to. It has worked fine with only authentication codes for a month.

**Comment by RyanTheAllmighty** [comment]
Superseded by #755
