### ISSUE TITLE
Error and freeze when attempting to collapse instances without a user account added

### ISSUE THREAD

**Issue by Tors-0** [ATLauncher/ATLauncher#770]
### What happened?

1. Open ATlauncher flatpak
2. import my instances from native version
3. attempt to collapse one of those instances (before logging into my minecraft account)
4. error message in console, launcher freezes

### Operating System

Linux

### Relevant log output

```shell
[10/06/2023 11:46:01 a.m.] java.lang.NullPointerException: Cannot read field "collapsedInstances" because the return value of "com.atlauncher.managers.AccountManager.getSelectedAccount()" is null
[10/06/2023 11:46:01 a.m.] 	at com.atlauncher.managers.InstanceManager.setInstanceVisbility(InstanceManager.java:156)
[10/06/2023 11:46:01 a.m.] 	at com.atlauncher.gui.components.CollapsiblePanel$ExpandAndCollapseAction.actionPerformed(CollapsiblePanel.java:299)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[10/06/2023 11:46:01 a.m.] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[10/06/2023 11:46:01 a.m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[10/06/2023 11:46:01 a.m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
[10/06/2023 11:46:01 a.m.] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[10/06/2023 11:46:01 a.m.] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[10/06/2023 11:46:01 a.m.] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Doomsdayrs** [comment]
Flatpak dev here,

After you added an account, were you able to collapse instances?

**Comment by RyanTheAllmighty** [comment]
Had this happen with someone else on Linux, but for servers with no account:

```
[02/07/2023 21:19:21 PM] Organising filesystem
[02/07/2023 21:19:21 PM] ATLauncher Version: 3.4.28.1 [9123cdc03237c5c3efa5dd8a1e8dffeaff0f5770]
[02/07/2023 21:19:21 PM] App Arguments: ["--working-dir\u003d**USERSDIR**"]
[02/07/2023 21:19:21 PM] JVM Arguments: []
[02/07/2023 21:19:21 PM] Java Version: Java 19 (19.0.2)
[02/07/2023 21:19:21 PM] Java Path: /nix/store/fky9a7is67fix3ma6g6c631ck0axv4v4-openjdk-19.0.2+7/lib/openjdk
[02/07/2023 21:19:21 PM] 64 Bit Java: true
[02/07/2023 21:19:21 PM] RAM Available: 15926MB
[02/07/2023 21:19:21 PM] Launcher Directory: **USERSDIR**
[02/07/2023 21:19:21 PM] GPU: TU106 [GeForce RTX 2070 Rev. A] (NVIDIA Corporation (0x10de)) unknown 288MB VRAM
[02/07/2023 21:19:21 PM] CPU: AMD Ryzen 5 2600X Six-Core Processor 6 cores/12 threads
[02/07/2023 21:19:21 PM] Operating System: NixOS (23.05 (Stoat) build 6.1.35)
[02/07/2023 21:19:21 PM] Bitness: 64
[02/07/2023 21:19:21 PM] Uptime: 14137
[02/07/2023 21:19:21 PM] Manufacturer: GNU/Linux
[02/07/2023 21:22:25 PM] java.lang.NullPointerException: Cannot read field "collapsedServers" because the return value of "com.atlauncher.managers.AccountManager.getSelectedAccount()" is null
[02/07/2023 21:22:25 PM] 	at com.atlauncher.managers.ServerManager.setServerVisibility(ServerManager.java:98)
[02/07/2023 21:22:25 PM] 	at com.atlauncher.gui.components.CollapsiblePanel$ExpandAndCollapseAction.actionPerformed(CollapsiblePanel.java:302)
[02/07/2023 21:22:25 PM] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[02/07/2023 21:22:25 PM] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[02/07/2023 21:22:25 PM] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[02/07/2023 21:22:25 PM] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[02/07/2023 21:22:25 PM] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
[02/07/2023 21:22:25 PM] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[02/07/2023 21:22:25 PM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[02/07/2023 21:22:25 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[02/07/2023 21:22:25 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[02/07/2023 21:22:25 PM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[02/07/2023 21:22:25 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[02/07/2023 21:22:25 PM] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Tors-0** [comment]
> Flatpak dev here,
> 
> After you added an account, were you able to collapse instances?

yes i was, although this issue seems to have already been fixed
