### ISSUE TITLE
Unable to create instances: `resources.download.minecraft.net` responds with HTTP 429

### ISSUE THREAD

**Issue by rijenkii** [ATLauncher/ATLauncher#771]
### What happened?

1. Open ATLauncher
2. Started creating and instance of vanilla 1.18.2.
3. After a while, installation will fail.

In logs there is a message that request to `resources.download.minecraft.net` failed with HTTP 429.
Thankfully ATLauncher saved already downloaded files, so after about 5 tries instance downloaded fully.

I think this can be fixed by not hard-failing on 429, instead by sleeping for couple seconds before retrying.

### Operating System

Windows

### Relevant log output

```shell
[12/06/2023 15:09:42 PM] Started install of Minecraft version 1.18.2
[12/06/2023 15:09:45 PM] Error trying to download b88bd8618c05232a7287799ea9246ae12f5da9d5
[12/06/2023 15:09:45 PM] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/b8/b88bd8618c05232a7287799ea9246ae12f5da9d5 request wasn't successful: Response{protocol=h2, code=429, message=, url=https://resources.download.minecraft.net/b8/b88bd8618c05232a7287799ea9246ae12f5da9d5}
[12/06/2023 15:09:45 PM] 	at com.atlauncher.network.Download.execute(Download.java:323)
[12/06/2023 15:09:45 PM] 	at com.atlauncher.network.Download.downloadFile(Download.java:598)
[12/06/2023 15:09:45 PM] 	at com.atlauncher.network.Download.downloadFile(Download.java:556)
[12/06/2023 15:09:45 PM] 	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
[12/06/2023 15:09:45 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12/06/2023 15:09:45 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12/06/2023 15:09:45 PM] 	at java.base/java.lang.Thread.run(Unknown Source)
[12/06/2023 15:09:45 PM] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/b8/b88bd8618c05232a7287799ea9246ae12f5da9d5 request wasn't successful: Response{protocol=h2, code=429, message=, url=https://resources.download.minecraft.net/b8/b88bd8618c05232a7287799ea9246ae12f5da9d5}
	at com.atlauncher.network.Download.execute(Download.java:323)
	at com.atlauncher.network.Download.downloadFile(Download.java:598)
	at com.atlauncher.network.Download.downloadFile(Download.java:556)
	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
These rules on the Minecraft cdn seem to have been added more recently. It also seems to be something that isn't targetted at everyone, I have yet to see it, even on a complete new install.

Would be good to understand what the rate limit is that it's hitting and see if there's any headers that tell us when it resets and how many are left, might be able to automate around it.

It shouldn't exist on a static cdn in the first place, but will look into trying to replicate it.

**Comment by RyanTheAllmighty** [comment]
No matter how many requests I throw at downloading the resources, I cannot get the 429 response. Unless it's time based on Microsofts side rather than based on user behaviour.

I think from my side all I can do for now is print out response headers to console when there is a 429 and try and make some solution based off user logs when they come in

**Comment by RyanTheAllmighty** [comment]
Even after logging the headers, no sort of rate limiting headers are returned...

**Comment by rijenkii** [comment]
Still getting 429, here are the logs:

<details><summary>logs</summary>

```
[10/08/2023 17:17:17 PM] Organising filesystem
[10/08/2023 17:17:17 PM] Unknown language English. Defaulting to английский
[10/08/2023 17:17:17 PM] ATLauncher Version: 3.4.31.2 [9edcfef7a39228bb53bb004661c090bacb65566a]
[10/08/2023 17:17:17 PM] App Arguments: []
[10/08/2023 17:17:17 PM] JVM Arguments: ["-Djna.nosys=true","-Djava.net.preferIPv4Stack=true","-Dawt.useSystemAAFontSettings=on","-Dswing.aatext=true"]
[10/08/2023 17:17:17 PM] Java Version: Java 17 (17.0.3)
[10/08/2023 17:17:17 PM] Java Path: C:\Program Files\Eclipse Adoptium\jre-17.0.7.7-hotspot
[10/08/2023 17:17:17 PM] 64 Bit Java: true
[10/08/2023 17:17:17 PM] RAM Available: 32103MB
[10/08/2023 17:17:17 PM] Launcher Directory: **USERSDIR**
[10/08/2023 17:17:18 PM] GPU: AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc. (0x1002)) DriverVersion=31.0.12024.0 512MB VRAM
[10/08/2023 17:17:18 PM] CPU: AMD Ryzen 5 5600G with Radeon Graphics 6 cores/12 threads
[10/08/2023 17:17:18 PM] Operating System: Windows (10 build 19045)
[10/08/2023 17:17:18 PM] Bitness: 64
[10/08/2023 17:17:18 PM] Uptime: 1534919
[10/08/2023 17:17:18 PM] Manufacturer: Microsoft
[10/08/2023 17:17:18 PM] Showing splash screen and loading everything
[10/08/2023 17:17:18 PM] Checking for updated files!
[10/08/2023 17:17:20 PM] Finished downloading updated files!
[10/08/2023 17:17:21 PM] Launcher finished loading everything
[10/08/2023 17:17:21 PM] Launcher not setup. Loading Setup Dialog
[10/08/2023 17:17:23 PM] Launcher opening
[10/08/2023 17:17:23 PM] Made By Bob*
[10/08/2023 17:17:23 PM] *(Not Actually)
[10/08/2023 17:17:23 PM] Setting up Bottom Bar
[10/08/2023 17:17:23 PM] Finished Setting up Bottom Bar
[10/08/2023 17:17:23 PM] Setting up Tabs
[10/08/2023 17:17:23 PM] Finished Setting up Tabs
[10/08/2023 17:17:23 PM] Showing Launcher
[10/08/2023 17:18:28 PM] Added Microsoft Account Rijenkii
[10/08/2023 17:18:28 PM] Downloading skin for Rijenkii
[10/08/2023 17:18:28 PM] Changed account to Rijenkii
[10/08/2023 17:18:40 PM] Started install of Minecraft version 1.20.1
[10/08/2023 17:18:57 PM] date: Thu, 10 Aug 2023 10:18:57 GMT
content-type: text/html
content-length: 1261
cache-control: no-store
x-azure-ref: 20230810T101857Z-1m3nu0qdet3v78fqkbfmz2zq7800000002yg000000004qq1
x-cache: CONFIG_NOCACHE
[10/08/2023 17:18:57 PM] Error trying to download 4ecfe93a57707c258fbd48b0b4c100686169dcce
[10/08/2023 17:18:57 PM] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/4e/4ecfe93a57707c258fbd48b0b4c100686169dcce request wasn't successful: Response{protocol=h2, code=429, message=, url=https://resources.download.minecraft.net/4e/4ecfe93a57707c258fbd48b0b4c100686169dcce}
[10/08/2023 17:18:57 PM] 	at com.atlauncher.network.Download.execute(Download.java:333)
[10/08/2023 17:18:57 PM] 	at com.atlauncher.network.Download.downloadFile(Download.java:618)
[10/08/2023 17:18:57 PM] 	at com.atlauncher.network.Download.downloadFile(Download.java:574)
[10/08/2023 17:18:57 PM] 	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
[10/08/2023 17:18:57 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[10/08/2023 17:18:57 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[10/08/2023 17:18:57 PM] 	at java.base/java.lang.Thread.run(Unknown Source)
[10/08/2023 17:18:57 PM] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/4e/4ecfe93a57707c258fbd48b0b4c100686169dcce request wasn't successful: Response{protocol=h2, code=429, message=, url=https://resources.download.minecraft.net/4e/4ecfe93a57707c258fbd48b0b4c100686169dcce}
	at com.atlauncher.network.Download.execute(Download.java:333)
	at com.atlauncher.network.Download.downloadFile(Download.java:618)
	at com.atlauncher.network.Download.downloadFile(Download.java:574)
	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[10/08/2023 17:19:47 PM] Started install of Minecraft version 1.20.1
[10/08/2023 17:20:25 PM] date: Thu, 10 Aug 2023 10:20:25 GMT
content-type: text/html
content-length: 1261
cache-control: no-store
x-azure-ref: 20230810T102025Z-mx99110kv9093a0zyb8xmd73ks000000055000000000e2bw
x-cache: CONFIG_NOCACHE
[10/08/2023 17:20:25 PM] Error trying to download 2a42ff969529927ccafc8e0d81c426da8f4e5160
[10/08/2023 17:20:25 PM] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/2a/2a42ff969529927ccafc8e0d81c426da8f4e5160 request wasn't successful: Response{protocol=h2, code=429, message=, url=https://resources.download.minecraft.net/2a/2a42ff969529927ccafc8e0d81c426da8f4e5160}
[10/08/2023 17:20:25 PM] 	at com.atlauncher.network.Download.execute(Download.java:333)
[10/08/2023 17:20:25 PM] 	at com.atlauncher.network.Download.downloadFile(Download.java:618)
[10/08/2023 17:20:25 PM] 	at com.atlauncher.network.Download.downloadFile(Download.java:574)
[10/08/2023 17:20:25 PM] 	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
[10/08/2023 17:20:25 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[10/08/2023 17:20:25 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[10/08/2023 17:20:25 PM] 	at java.base/java.lang.Thread.run(Unknown Source)
[10/08/2023 17:20:25 PM] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/2a/2a42ff969529927ccafc8e0d81c426da8f4e5160 request wasn't successful: Response{protocol=h2, code=429, message=, url=https://resources.download.minecraft.net/2a/2a42ff969529927ccafc8e0d81c426da8f4e5160}
	at com.atlauncher.network.Download.execute(Download.java:333)
	at com.atlauncher.network.Download.downloadFile(Download.java:618)
	at com.atlauncher.network.Download.downloadFile(Download.java:574)
	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by RyanTheAllmighty** [comment]
@rijenkii if you visit https://resources.download.minecraft.net/2a/2a42ff969529927ccafc8e0d81c426da8f4e5160 in your browser, is it downloading a file or showing a webpage? If it's showing a webpage that would be useful to know what it's saying when you end up getting the 429 response

**Comment by rijenkii** [comment]
Sadly no, It always stops on a different resource and that resource always opens in the browser afterwards.
And because it's https, I can't even sniff it with wireshark..

**Comment by RyanTheAllmighty** [comment]
I've tried to replicate it with a VPN into smaller countries and countries that people have had the issue in, and still never managed to replicate it.

As far as I can tell were the only launcher that seems to run into this issue. 

Next step I think I'd to print out that HTML it's returning when it happens (we already had logic to do this previously, so not sure why that's not working here).

Only other thing I can think of is the number of concurrent connections. Vanilla launcher only died it single threaded I believe, and we use 8 by default, maybe that's part of the issue. If you're still getting it @rijenkii maybe try lowering the concurrent connections in the launchers network settings and see if it helps.

**Comment by rijenkii** [comment]
> I've tried to replicate it with a VPN into smaller countries and countries that people have had the issue in, and still never managed to replicate it.

Russia.

> maybe try lowering the concurrent connections in the launchers network settings and see if it helps.

So, frustratingly, I'm now unable to get the error on 1, 8 or 64 concurrent connections.
Will try again later.

**Comment by Nauhai** [comment]
I got the same issue here, and i fixed it by checking "don't use HTTP/2" in network settings!

**Comment by RyanTheAllmighty** [comment]
Going to turn off HTTP/2 connections completely in the launcher to try and solve this issue
