### ISSUE TITLE
Cannot update multiple mods

### ISSUE THREAD

**Issue by nijahplays** [ATLauncher/ATLauncher#772]
### What happened?

Open a large modpack and select all

Press check for updates

Freezes and throws an error

### Operating System

Linux

### Relevant log output

```shell
[14/06/2023 02:47:41 AM] Organising filesystem
[14/06/2023 02:47:41 AM] ATLauncher Version: 3.4.28.1 [9123cdc03237c5c3efa5dd8a1e8dffeaff0f5770]
[14/06/2023 02:47:41 AM] App Arguments: ["--install-method\u003daur-bin","--no-launcher-update"]
[14/06/2023 02:47:41 AM] JVM Arguments: ["-Dawt.useSystemAAFontSettings\u003don","-Dswing.aatext\u003dtrue"]
[14/06/2023 02:47:41 AM] Java Version: Java 20 (20.0.1)
[14/06/2023 02:47:41 AM] Java Path: /usr/lib/jvm/java-20-openjdk
[14/06/2023 02:47:41 AM] 64 Bit Java: true
[14/06/2023 02:47:41 AM] RAM Available: 15903MB
[14/06/2023 02:47:41 AM] Launcher Directory: **USERSDIR**
[14/06/2023 02:47:41 AM] GPU: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)) unknown 8194MB VRAM
[14/06/2023 02:47:42 AM] CPU: AMD Ryzen 7 1700 Eight-Core Processor 8 cores/16 threads
[14/06/2023 02:47:42 AM] Operating System: Manjaro Linux (unknown (unknown) build 6.3.7-1-MANJARO)
[14/06/2023 02:47:42 AM] Bitness: 64
[14/06/2023 02:47:42 AM] Uptime: 21565
[14/06/2023 02:47:42 AM] Manufacturer: GNU/Linux
[14/06/2023 02:47:42 AM] Showing splash screen and loading everything
[14/06/2023 02:47:42 AM] Checking for updated files!
[14/06/2023 02:47:42 AM] Checking for updates to Modrinth instances
[14/06/2023 02:47:42 AM] Launcher finished loading everything
[14/06/2023 02:47:42 AM] Launcher opening
[14/06/2023 02:47:42 AM] Made By Bob*
[14/06/2023 02:47:42 AM] *(Not Actually)
[14/06/2023 02:47:42 AM] Setting up Bottom Bar
[14/06/2023 02:47:42 AM] Finished Setting up Bottom Bar
[14/06/2023 02:47:42 AM] Setting up Tabs
[14/06/2023 02:47:43 AM] Finished Setting up Tabs
[14/06/2023 02:47:43 AM] Showing Launcher
[14/06/2023 02:47:49 AM] java.lang.IllegalArgumentException: Window must not be zero
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:312)
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1676)
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.XWindowPeer.restoreTransientFor(XWindowPeer.java:1852)
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.XWindowPeer.removeFromTransientFors(XWindowPeer.java:1916)
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1630)
[14/06/2023 02:47:49 AM] 	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1602)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Window.setModalBlocked(Window.java:1535)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Dialog.unblockWindow(Dialog.java:1569)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Window.updateChildrenBlocking(Window.java:1763)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Dialog.modalShow(Dialog.java:1437)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Dialog.modalHide(Dialog.java:1463)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Dialog.hideAndDisposePreHandler(Dialog.java:1130)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Dialog.hide(Dialog.java:1159)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Component.show(Component.java:1730)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
[14/06/2023 02:47:49 AM] 	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
[14/06/2023 02:47:49 AM] 	at com.atlauncher.gui.dialogs.ProgressDialog.close(ProgressDialog.java:157)
[14/06/2023 02:47:49 AM] 	at com.atlauncher.gui.dialogs.EditModsDialog.lambda$checkForUpdates$19(EditModsDialog.java:408)
[14/06/2023 02:47:49 AM] 	at java.base/java.lang.Thread.run(Thread.java:1623)
[14/06/2023 02:47:49 AM] java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
	at java.desktop/sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:312)
	at java.desktop/sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1676)
	at java.desktop/sun.awt.X11.XWindowPeer.restoreTransientFor(XWindowPeer.java:1852)
	at java.desktop/sun.awt.X11.XWindowPeer.removeFromTransientFors(XWindowPeer.java:1916)
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1630)
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1602)
	at java.desktop/java.awt.Window.setModalBlocked(Window.java:1535)
	at java.desktop/java.awt.Dialog.unblockWindow(Dialog.java:1569)
	at java.desktop/java.awt.Window.updateChildrenBlocking(Window.java:1763)
	at java.desktop/java.awt.Dialog.modalShow(Dialog.java:1437)
	at java.desktop/java.awt.Dialog.modalHide(Dialog.java:1463)
	at java.desktop/java.awt.Dialog.hideAndDisposePreHandler(Dialog.java:1130)
	at java.desktop/java.awt.Dialog.hide(Dialog.java:1159)
	at java.desktop/java.awt.Component.show(Component.java:1730)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at com.atlauncher.gui.dialogs.ProgressDialog.close(ProgressDialog.java:157)
	at com.atlauncher.gui.dialogs.EditModsDialog.lambda$checkForUpdates$19(EditModsDialog.java:408)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Additional Information

https://paste.atlauncher.com/view/6c22c370-1519-4ed6-9d48-eb554876dab1

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nijahplays** [comment]
Does this with any Desktop environment

I am using Wayland

**Comment by RyanTheAllmighty** [comment]
From #699 

-----

**Describe the bug**
After updating mods in the edit mods menu hangs because of "Window must not be zero" => unable to update any mods via launcher

**To Reproduce**
Steps to reproduce the behavior:
1. Click edit mods on an instance (1.19.2 with fabric in my case) 
2. Select any mod
3. Click "Check for updates"
4. Add any available updates
5. Right after it finishes it hangs on "Checking for updates"

**Logs**
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:56)
	at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(WindowPropertyGetter.java:73)
	at java.desktop/sun.awt.X11.XlibUtil.isToplevelWindow(XlibUtil.java:312)
	at java.desktop/sun.awt.X11.XWindowPeer.setToplevelTransientFor(XWindowPeer.java:1676)
	at java.desktop/sun.awt.X11.XWindowPeer.restoreTransientFor(XWindowPeer.java:1852)
	at java.desktop/sun.awt.X11.XWindowPeer.removeFromTransientFors(XWindowPeer.java:1916)
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1630)
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(XWindowPeer.java:1602)
	at java.desktop/java.awt.Window.setModalBlocked(Window.java:1535)
	at java.desktop/java.awt.Dialog.unblockWindow(Dialog.java:1569)
	at java.desktop/java.awt.Window.updateChildrenBlocking(Window.java:1763)
	at java.desktop/java.awt.Dialog.modalShow(Dialog.java:1437)
	at java.desktop/java.awt.Dialog.modalHide(Dialog.java:1463)
	at java.desktop/java.awt.Dialog.hideAndDisposePreHandler(Dialog.java:1130)
	at java.desktop/java.awt.Dialog.hide(Dialog.java:1159)
	at java.desktop/java.awt.Component.show(Component.java:1730)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at com.atlauncher.gui.dialogs.ProgressDialog.close(ProgressDialog.java:157)
	at com.atlauncher.gui.dialogs.EditModsDialog.lambda$checkForUpdates$19(EditModsDialog.java:403)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Screenshots**
![image](https://user-images.githubusercontent.com/57142641/210768985-41e27fbc-cf06-40e3-8e66-62113a388574.png)

**System information (please complete the following information, or remove if not applicable):**
- OS: Arch Linux with linux 6.1.1
- Java Version: openjdk version "19.0.1" 2022-10-18

**Comment by Einhornyordle** [comment]
Same issue here, it doesn't happen all the time, but I'd say about 90-95% when I try to check multiple mods at once.

AT Launcher Log: https://paste.atlauncher.com/view/a4f8fe2a-3431-4608-acd0-69e84a1a05ce
OS: Linux Mint 21.2
Full System Info: https://termbin.com/9xff
Java:
```
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

**Comment by CarlosGT7274** [comment]
> Same issue here, it doesn't happen all the time, but I'd say about 90-95% when I try to check multiple mods at once.
> 
> AT Launcher Log: https://paste.atlauncher.com/view/a4f8fe2a-3431-4608-acd0-69e84a1a05ce OS: Linux Mint 21.2 Full System Info: https://termbin.com/9xff Java:
> 
> ```
> openjdk version "17.0.8.1" 2023-08-24
> OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
> OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)
> ```

you resolved it?

**Comment by Einhornyordle** [comment]
Nope, hat the issue multiple times today again
