### ISSUE TITLE
Clicking the Settings button on any instance is unresponsive, causes app to hang

### ISSUE THREAD

**Issue by MAO3J1m0Op** [ATLauncher/ATLauncher#776]
### What happened?

When I click the settings button of any of my instances, the popup does not appear; instead, I see the console populate with the stack trace of an `IndexOutOfBoundsException`. Clicking the settings button again after this point causes the app to stop responding. I have found that this issue affects both my macOS application install and the Jar install.

Steps to reproduce:
1. Open ATLauncher
2. Click the settings button of any instance.
3. Check console; click settings again to hang the app

### Operating System

macOS

### Relevant log output

```shell
[22/06/2023 11:20:27 AM] java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[22/06/2023 11:20:27 AM] 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[22/06/2023 11:20:27 AM] 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[22/06/2023 11:20:27 AM] 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[22/06/2023 11:20:27 AM] 	at java.base/java.util.Objects.checkIndex(Objects.java:361)
[22/06/2023 11:20:27 AM] 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[22/06/2023 11:20:27 AM] 	at com.atlauncher.gui.dialogs.instancesettings.JavaInstanceSettingsTab.setupComponents(JavaInstanceSettingsTab.java:449)
[22/06/2023 11:20:27 AM] 	at com.atlauncher.gui.dialogs.instancesettings.JavaInstanceSettingsTab.<init>(JavaInstanceSettingsTab.java:97)
[22/06/2023 11:20:27 AM] 	at com.atlauncher.gui.dialogs.InstanceSettingsDialog.<init>(InstanceSettingsDialog.java:70)
[22/06/2023 11:20:27 AM] 	at com.atlauncher.gui.card.InstanceCard.lambda$addActionListeners$33(InstanceCard.java:476)
[22/06/2023 11:20:27 AM] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[22/06/2023 11:20:27 AM] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[22/06/2023 11:20:27 AM] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[22/06/2023 11:20:27 AM] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[22/06/2023 11:20:27 AM] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
[22/06/2023 11:20:27 AM] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[22/06/2023 11:20:27 AM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[22/06/2023 11:20:27 AM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[22/06/2023 11:20:27 AM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
[22/06/2023 11:20:27 AM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[22/06/2023 11:20:27 AM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[22/06/2023 11:20:27 AM] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[22/06/2023 11:20:27 AM] java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.atlauncher.gui.dialogs.instancesettings.JavaInstanceSettingsTab.setupComponents(JavaInstanceSettingsTab.java:449)
	at com.atlauncher.gui.dialogs.instancesettings.JavaInstanceSettingsTab.<init>(JavaInstanceSettingsTab.java:97)
	at com.atlauncher.gui.dialogs.InstanceSettingsDialog.<init>(InstanceSettingsDialog.java:70)
	at com.atlauncher.gui.card.InstanceCard.lambda$addActionListeners$33(InstanceCard.java:476)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[22/06/2023 11:32:12 AM]
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MAO3J1m0Op** [comment]
Fixed on my machine. Opening ATLauncher using an x86 Java SDK instead of an arm64 one seemed to do the trick.
