### ISSUE TITLE
MultiMC import not importing java arguments

### ISSUE THREAD

**Issue by mjevans** [ATLauncher/ATLauncher#779]
### What happened?

I have Multiple Java versions installed.
AT Launcher appears to ignore / disconnect Java Path from Java Executable selection.

Import the Java 17 (through 20) version of gtnewhorizons via their "MultiMC pack" link.

Switch to (Java) Azul Zulu-17 in the mod settings

It showed up in one of my launches, but the _wrong_ Java Path was initialized, even though it had been customized in the instance settings.

As troubleshooting I followed the same steps for importing the desired pack in the Prism launcher and it is able to launch the specified pack with the same settings.

### Operating System

Linux

### Relevant log output

```shell
[2023-07-07 19:31:48 PM] Console Cleared
[2023-07-07 19:31:59 PM] Preparing for launch!
[2023-07-07 19:31:59 PM] Launching pack GTNH 2.3.4 1 (MultiMcImport) for Minecraft 1.7.10
[2023-07-07 19:31:59 PM] Logging into Minecraft!
[2023-07-07 19:31:59 PM] Loader: Forge 10.13.4.1614
[2023-07-07 19:31:59 PM] Mods:
... Removed the shipped journeymap and hardcore darkness
[2023-07-07 19:31:59 PM]  - /CustomPlayerModels-1.7.10-0.6.9a.jar (Added)
[2023-07-07 19:31:59 PM]  - /journeymap-1.7.10-5.1.4p3-unlimited.jar (Added)
[2023-07-07 19:31:59 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [/usr/lib/jvm/zulu-17/bin/java, -Xmx6144M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dlog4j.configurationFile=USERSDIR/assets/log_configs/client-1.7.xml, -Dlog4j2.formatMsgNoLookups=true, -XX:+UseG1GC, -Dsun.rmi.dgc.server.gcInterval=2147483646, -XX:+UnlockExperimentalVMOptions, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=32M, -Djava.library.path=USERSDIR/temp/natives-4d4ec115fd6d42da8e061a30010c0646, -cp, USERSDIR/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:USERSDIR/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar:USERSDIR/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar:USERSDIR/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar:USERSDIR/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar:USERSDIR/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar:USERSDIR/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar:USERSDIR/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar:USERSDIR/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar:USERSDIR/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar:USERSDIR/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar:USERSDIR/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar:USERSDIR/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar:USERSDIR/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar:USERSDIR/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar:USERSDIR/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:USERSDIR/libraries/com/google/guava/guava/17.0/guava-17.0.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:USERSDIR/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar:USERSDIR/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar:USERSDIR/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:USERSDIR/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:USERSDIR/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:USERSDIR/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:USERSDIR/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar:USERSDIR/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar:USERSDIR/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:USERSDIR/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:USERSDIR/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:USERSDIR/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:USERSDIR/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:USERSDIR/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:USERSDIR/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar:USERSDIR/libraries/com/google/guava/guava/15.0/guava-15.0.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:USERSDIR/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:USERSDIR/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:USERSDIR/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:USERSDIR/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:USERSDIR/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:USERSDIR/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar:USERSDIR/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar:USERSDIR/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar:USERSDIR/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-linux.jar:USERSDIR/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar:USERSDIR/libraries/net/minecraft/client/1.7.10/client-1.7.10.jar, net.minecraft.launchwrapper.Launch, --username, REDACTED, --version, 1.7.10, --gameDir, USERSDIR/instances/GTNH2341720, --assetsDir, USERSDIR/assets, --assetIndex, 1.7.10, --uuid, REDACTED, --accessToken, REDACTED, --userProperties, [], --userType, msa, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker, --width=854, --height=480]
[2023-07-07 19:32:00 PM] Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
[2023-07-07 19:32:00 PM] 	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
[2023-07-07 19:32:00 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[2023-07-07 19:32:00 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[2023-07-07 19:32:07 PM] Checking for updated files!
[2023-07-07 19:32:07 PM] Checking for updates to CurseForge instances
[2023-07-07 19:32:50 PM] Copied Log to clipboard
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Looks like it's using your Java path correctly, but 1.7.10 Minecraft, specifically forge I believe, only supports Java 8

**Comment by mjevans** [comment]
The Prism launcher does seem to add (or retain from the import?) a bunch of additional java arguments that I didn't configure otherwise.

Java 17 through 20 _do_ work with this pack, and while I was playing with a Java 8 version of the pack encountered render issues seemingly only resolved by launching this pack a different way.  Either the switch to the Java 17 version of the pack OR using a different launcher fixed the issue.  Which points towards two issues: the one I've raised here where it AT Launcher doesn't even start to get off the ground with Java 17, and the differences between running the pack in two different launchers and java versions yielding different results.  I don't know if it was the extra parameters (possible) or if it was the switch in Java version.

``` logfile
Java path is:
/usr/lib/jvm/zulu-17/bin/java
...
Java Arguments:
[-Dlog4j2.formatMsgNoLookups=true, -XX:+UseG1GC, -Dsun.rmi.dgc.server.gcInterval=2147483646, -XX:+UnlockExperimentalVMOptions, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=32M, --illegal-access=warn, -Djava.security.manager=allow, -Dfile.encoding=UTF-8, --add-opens, java.base/jdk.internal.loader=ALL-UNNAMED, --add-opens, java.base/java.net=ALL-UNNAMED, --add-opens, java.base/java.nio=ALL-UNNAMED, --add-opens, java.base/java.io=ALL-UNNAMED, --add-opens, java.base/java.lang=ALL-UNNAMED, --add-opens, java.base/java.lang.reflect=ALL-UNNAMED, --add-opens, java.base/java.text=ALL-UNNAMED, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.base/jdk.internal.reflect=ALL-UNNAMED, --add-opens, java.base/sun.nio.ch=ALL-UNNAMED, --add-opens, jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED,java.naming, --add-opens, java.desktop/sun.awt.image=ALL-UNNAMED, --add-opens, java.desktop/com.sun.imageio.plugins.png=ALL-UNNAMED, --add-modules, jdk.dynalink, --add-opens, jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED, --add-modules, java.sql.rowset, --add-opens, java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED, -Xms512m, -Xmx6144m, -Duser.language=en]

Minecraft process ID: 126349

OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
[21:29:28] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by cpw.mods.fml.common.launcher.FMLTweaker (file:/home/USERNAME/.local/share/PrismLauncher/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar)
WARNING: Please consider reporting this to the maintainers of cpw.mods.fml.common.launcher.FMLTweaker
WARNING: System::setSecurityManager will be removed in a future release
[21:29:28] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:29:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:29:28] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[21:29:28] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 17.0.7, running on Linux:amd64:6.4.1-arch2-1, installed at /usr/lib/jvm/zulu-17
...
Game launches and is fully playable.
```

**Comment by RyanTheAllmighty** [comment]
Ok the issue is not with the java path, that's showing fine, it's the extra Java arguments that aren't being passed. Where can I get the zip for this pack to replicate it?
