### ISSUE TITLE
Thinks the filesystem is in read mode

### ISSUE THREAD

**Issue by largenton** [ATLauncher/ATLauncher#790]
### What happened?

When exporting, it doesn't matter what format it is written in the console that "filesystem is in read mode". And in other programs and the launcher (the same prism), everything is in order! How to fix or is it a bug?

### Operating System

Linux

### Relevant log output

```shell
Failed to create zip /home/renceron/Загрузки/gear-2-branches 1.3.0.mrpack from **USERSDIR**/temp/GEAR2branches-export
[23/07/2023 19:13:12 PM] java.nio.file.FileSystemException: /home/renceron/Загрузки/gear-2-branches 1.3.0.mrpack: The file system is read-only
[23/07/2023 19:13:12 PM] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
[23/07/2023 19:13:12 PM] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[23/07/2023 19:13:12 PM] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[23/07/2023 19:13:12 PM] 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
[23/07/2023 19:13:12 PM] 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
[23/07/2023 19:13:12 PM] 	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
[23/07/2023 19:13:12 PM] 	at com.atlauncher.utils.ArchiveUtils.createZip(ArchiveUtils.java:218)
[23/07/2023 19:13:12 PM] 	at com.atlauncher.utils.ArchiveUtils.createZip(ArchiveUtils.java:202)
[23/07/2023 19:13:12 PM] 	at com.atlauncher.data.Instance.exportAsModrinthZip(Instance.java:2341)
[23/07/2023 19:13:12 PM] 	at com.atlauncher.data.Instance.export(Instance.java:1715)
[23/07/2023 19:13:12 PM] 	at com.atlauncher.gui.dialogs.InstanceExportDialog.lambda$null$3(InstanceExportDialog.java:296)
[23/07/2023 19:13:12 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[23/07/2023 19:13:12 PM] java.nio.file.FileSystemException: /home/renceron/Загрузки/gear-2-branches 1.3.0.mrpack: Файловая система доступна только для чтения
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
	at com.atlauncher.utils.ArchiveUtils.createZip(ArchiveUtils.java:218)
	at com.atlauncher.utils.ArchiveUtils.createZip(ArchiveUtils.java:202)
	at com.atlauncher.data.Instance.exportAsModrinthZip(Instance.java:2341)
	at com.atlauncher.data.Instance.export(Instance.java:1715)
	at com.atlauncher.gui.dialogs.InstanceExportDialog.lambda$null$3(InstanceExportDialog.java:296)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Additional Information

Install as Flatpack package on non-RPM and Fedora 38 system

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Doomsdayrs** [comment]
Flatpak maintainer here.

Thank you for notifying of this issue.

This is due to a security feature of flatpak to prevent an application from writing to unallowed locations. For example, if unconfined, the "fractureiser" malware would have theoretically been able to infect other jars on your system. Thankfully the flatpak sandbox prevents this.

Thus, the issue here is that the export dialog does not use the xdg file picker (which can allow access to a directory/file).

**Comment by largenton** [comment]
Thanks for the quick response, what should I do to get "xdg file picker" to work?

**Comment by largenton** [comment]
Thanks for the quick response, what should I do to get "xdg file picker" to work?

**Comment by Doomsdayrs** [comment]
Please open the issue again, I am currently working on a fix.
