### ISSUE TITLE
I cant open the folder of the packs

### ISSUE THREAD

**Issue by Robro0-625** [ATLauncher/ATLauncher#801]
### What happened?

Open ATLauncher 
click the 'open folder' 

expected result the folder opens

what actually happens a bunch of errors show up in the console

### Operating System

Linux

### Relevant log output

```shell
[10 August 2023 20:51:38 PM] Organising filesystem
[10 August 2023 20:51:39 PM] ATLauncher Version: 3.4.31.2 [a1c6bbc38806b3c09df1cc057c27571d8ec3e420]
[10 August 2023 20:51:39 PM] App Arguments: ["--working-dir=.var/app/com.atlauncher.ATLauncher/data/","--no-launcher-update"]
[10 August 2023 20:51:39 PM] JVM Arguments: ["-Dawt.useSystemAAFontSettings=on","-Dswing.aatext=true"]
[10 August 2023 20:51:39 PM] Java Version: Java 17 (17.0.7)
[10 August 2023 20:51:39 PM] Java Path: /app/jre
[10 August 2023 20:51:39 PM] 64 Bit Java: true
[10 August 2023 20:51:39 PM] RAM Available: 31708MB
[10 August 2023 20:51:39 PM] Launcher Directory: .var/app/com.atlauncher.ATLauncher/data
[10 August 2023 20:51:39 PM] Using Flatpak!
[10 August 2023 20:51:40 PM] GPU: TU104BM [GeForce RTX 2070 SUPER Mobile / Max-Q] (NVIDIA Corporation (0x10de)) unknown 288MB VRAM
[10 August 2023 20:51:40 PM] CPU: Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz 8 cores/16 threads
[10 August 2023 20:51:40 PM] Operating System: Freedesktop.org (21.08.20.1 (Flatpak runtime) build 6.2.0-26-generic)
[10 August 2023 20:51:40 PM] Bitness: 64
[10 August 2023 20:51:40 PM] Uptime: 75151
[10 August 2023 20:51:40 PM] Manufacturer: GNU/Linux
[10 August 2023 20:51:40 PM] Showing splash screen and loading everything
[10 August 2023 20:51:40 PM] Checking for updated files!
[10 August 2023 20:51:41 PM] Checking for updates to CurseForge instances
[10 August 2023 20:51:41 PM] Launcher finished loading everything
[10 August 2023 20:51:41 PM] Launcher opening
[10 August 2023 20:51:41 PM] Made By Bob*
[10 August 2023 20:51:41 PM] *(Not Actually)
[10 August 2023 20:51:41 PM] Setting up Bottom Bar
[10 August 2023 20:51:41 PM] Finished Setting up Bottom Bar
[10 August 2023 20:51:41 PM] Setting up Tabs
[10 August 2023 20:51:41 PM] Checking for updates to Modrinth instances
[10 August 2023 20:51:42 PM] Finished Setting up Tabs
[10 August 2023 20:51:42 PM] Showing Launcher
[10 August 2023 20:51:48 PM] Error opening file explorer!
[10 August 2023 20:51:48 PM] java.io.IOException: Failed to show URI:file:**USERSDIR**/
[10 August 2023 20:51:48 PM] 	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
[10 August 2023 20:51:48 PM] 	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
[10 August 2023 20:51:48 PM] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:207)
[10 August 2023 20:51:48 PM] 	at com.atlauncher.utils.OS.openFileExplorer(OS.java:189)
[10 August 2023 20:51:48 PM] 	at com.atlauncher.gui.components.LauncherBottomBar.lambda$setupListeners$1(LauncherBottomBar.java:96)
[10 August 2023 20:51:48 PM] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[10 August 2023 20:51:48 PM] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[10 August 2023 20:51:48 PM] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[10 August 2023 20:51:48 PM] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[10 August 2023 20:51:48 PM] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
[10 August 2023 20:51:48 PM] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[10 August 2023 20:51:48 PM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[10 August 2023 20:51:48 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[10 August 2023 20:51:48 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
[10 August 2023 20:51:48 PM] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[10 August 2023 20:51:48 PM] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[10 August 2023 20:51:48 PM] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[10 August 2023 20:51:48 PM] java.io.IOException: Failed to show URI:file:**USERSDIR**/
	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
	at java.desktop/sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:87)
	at java.desktop/java.awt.Desktop.open(Desktop.java:431)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:207)
	at com.atlauncher.utils.OS.openFileExplorer(OS.java:189)
	at com.atlauncher.gui.components.LauncherBottomBar.lambda$setupListeners$1(LauncherBottomBar.java:96)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Can you share more information about your environment, such as Distro, version, window environment, file manager you use and desktop environment so we can try and replicate

**Comment by Doomsdayrs** [comment]
> Can you share more information about your environment, such as Distro, version, window environment, file manager you use and desktop environment so we can try and replicate

Its flatpak, the experience is the same on all environments.

It seems that the value `**USERDiR**` is being provided?

**Comment by RyanTheAllmighty** [comment]
> > Can you share more information about your environment, such as Distro, version, window environment, file manager you use and desktop environment so we can try and replicate
> 
> Its flatpak, the experience is the same on all environments.
> 
> It seems that the value `**USERDiR**` is being provided?

`**USERSDIR**` is just in the logs to censor the users install directory, only happens when logging to the console, it won't actually be getting that value

**Comment by Doomsdayrs** [comment]
Running ATLauncher on my system via flatpak, I find that clicking `Open Folder` to properly open up the folder of `ATLauncher`.

To confirm it was not my custom directory, by using default settings I still found `Open Folder` to operate as expected.

What distribution are you using? As it seems that flatpak or its dependencies are not properly configured.

**Comment by Doomsdayrs** [comment]
This may be related to #713

**Comment by Robro0-625** [comment]
im using Kubuntu KDE (x11)

**Comment by AideeAmei** [comment]
Is this related?

aideeamei@ameicorp:~$ sudo strace -ff -e trace=execve -s 200 -p 8865
strace: Process 8865 attached with 171 threads
[pid  9032] +++ exited with 0 +++
strace: Process 9305 attached
[pid  9305] execve("/home/aideeamei/.var/app/com.atlauncher.ATLauncher/data/runtimes/minecraft/java-runtime-epsilon/linux/java-runtime-epsilon/lib/jspawnhelper", ["/home/aideeamei/.var/app/com.atlauncher.ATLauncher/data/runtimes/minecraft/java-runtime-epsilon/linux/java-runtime-epsilon/lib/jspawnhelper", "25.0.1+8-LTS", "677:690:692"], 0x7ffff75fbd30 /* 86 vars */) = 0
[pid  9305] execve("/app/jre/bin/xdg-open", ["xdg-open", "file://///home/aideeamei/.var/app/com.atlauncher.ATLauncher/data/instances/Update/resourcepacks/"], 0x7ffd4ad0c298 /* 86 vars */) = -1 ENOENT (No such file or directory)
[pid  9305] execve("/usr/bin/xdg-open", ["xdg-open", "file://///home/aideeamei/.var/app/com.atlauncher.ATLauncher/data/instances/Update/resourcepacks/"], 0x7ffd4ad0c298 /* 86 vars */) = 0
[pid  9305] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=615, si_uid=1000} ---
[pid  9305] +++ killed by SIGPIPE +++
[pid  8881] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=615, si_uid=1000, si_status=SIGPIPE, si_utime=0, si_stime=0} ---
[pid  8881] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---

aideeamei@ameicorp:~$ sudo journalctl -f --since "now" | grep -Ei "xdg-desktop-portal|portal|flatpak|com\.atlauncher\.ATLauncher|xdg-open|gio"
Jul 28 09:09:08 ameicorp gamemoded[8869]: ERROR: Addition requested for already known client 9351 [/home/aideeamei/.var/app/com.atlauncher.ATLauncher/data/runtimes/minecraft/java-runtime-epsilon/linux/java-runtime-epsilon/lib/jspawnhelper].

Folders open by ATL directly open fine, folders open by Minecraft don't open. ATL console doesn't say anything at the time of clicking for example the resource packs folder button.
