### ISSUE TITLE
Importing FoxLoader MultiMC instance fails

### ISSUE THREAD

**Issue by CoolCat467** [ATLauncher/ATLauncher#855]
### What happened?

1. Open ATLauncher
2. Click `Import` button
3. Paste link to MultiMC zip from latest FoxLoader release https://github.com/Fox2Code/FoxLoader/releases/
(current link as of writing is https://github.com/Fox2Code/FoxLoader/releases/download/1.2.25/FoxLoader-1.2.25-mmc.zip)
4. After a second or two, `Failed To Import Instance` error message appears (first console dump)
5. After looking into the file myself and replacing `no-op` fields with valid versions (FoxLoader-1.2.26-mmc-2.zip), we get second console dump.
[FoxLoader-1.2.26-mmc-2.zip](https://github.com/ATLauncher/ATLauncher/files/13462653/FoxLoader-1.2.26-mmc-2.zip)

### Operating System

Windows

### Relevant log output

```shell
First console dump:

[24/11/2023 18:34:37 PM] Console Cleared
[24/11/2023 18:34:40 PM] No Minecraft version found matching no-op
[24/11/2023 18:34:40 PM] Failed to install MultiMC pack
[24/11/2023 18:34:40 PM] java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.atlauncher.data.Pack.getVersions()" is null
[24/11/2023 18:34:40 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.setVersionsDropdown(InstanceInstallerDialog.java:1068)
[24/11/2023 18:34:40 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.setupVersionsDropdown(InstanceInstallerDialog.java:1014)
[24/11/2023 18:34:40 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:292)
[24/11/2023 18:34:40 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:162)
[24/11/2023 18:34:40 PM] 	at com.atlauncher.utils.ImportPackUtils.loadMultiMCFormat(ImportPackUtils.java:399)
[24/11/2023 18:34:40 PM] 	at com.atlauncher.utils.ImportPackUtils.loadFromFile(ImportPackUtils.java:256)
[24/11/2023 18:34:40 PM] 	at com.atlauncher.utils.ImportPackUtils.loadFromUrl(ImportPackUtils.java:67)
[24/11/2023 18:34:40 PM] 	at com.atlauncher.gui.dialogs.ImportInstanceDialog.lambda$null$1(ImportInstanceDialog.java:223)
[24/11/2023 18:34:40 PM] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[24/11/2023 18:34:40 PM] java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.atlauncher.data.Pack.getVersions()" is null
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.setVersionsDropdown(InstanceInstallerDialog.java:1068)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.setupVersionsDropdown(InstanceInstallerDialog.java:1014)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:292)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:162)
	at com.atlauncher.utils.ImportPackUtils.loadMultiMCFormat(ImportPackUtils.java:399)
	at com.atlauncher.utils.ImportPackUtils.loadFromFile(ImportPackUtils.java:256)
	at com.atlauncher.utils.ImportPackUtils.loadFromUrl(ImportPackUtils.java:67)
	at com.atlauncher.gui.dialogs.ImportInstanceDialog.lambda$null$1(ImportInstanceDialog.java:223)
	at java.base/java.lang.Thread.run(Thread.java:1583)


Second console dump:
```console
[24/11/2023 18:36:22 PM] Console Cleared
[24/11/2023 18:36:32 PM] Failed to install MultiMC pack
[24/11/2023 18:36:32 PM] java.lang.NullPointerException: Cannot read field "uid" because "c" is null
[24/11/2023 18:36:32 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.lambda$handleMultiMcImport$26(InstanceInstallerDialog.java:820)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[24/11/2023 18:36:32 PM] 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[24/11/2023 18:36:32 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.handleMultiMcImport(InstanceInstallerDialog.java:820)
[24/11/2023 18:36:32 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:229)
[24/11/2023 18:36:32 PM] 	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:162)
[24/11/2023 18:36:32 PM] 	at com.atlauncher.utils.ImportPackUtils.loadMultiMCFormat(ImportPackUtils.java:399)
[24/11/2023 18:36:32 PM] 	at com.atlauncher.utils.ImportPackUtils.loadFromFile(ImportPackUtils.java:261)
[24/11/2023 18:36:32 PM] 	at com.atlauncher.gui.dialogs.ImportInstanceDialog.lambda$null$1(ImportInstanceDialog.java:227)
[24/11/2023 18:36:32 PM] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[24/11/2023 18:36:32 PM] java.lang.NullPointerException: Cannot read field "uid" because "c" is null
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.lambda$handleMultiMcImport$26(InstanceInstallerDialog.java:820)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.handleMultiMcImport(InstanceInstallerDialog.java:820)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:229)
	at com.atlauncher.gui.dialogs.InstanceInstallerDialog.<init>(InstanceInstallerDialog.java:162)
	at com.atlauncher.utils.ImportPackUtils.loadMultiMCFormat(ImportPackUtils.java:399)
	at com.atlauncher.utils.ImportPackUtils.loadFromFile(ImportPackUtils.java:261)
	at com.atlauncher.gui.dialogs.ImportInstanceDialog.lambda$null$1(ImportInstanceDialog.java:227)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[24/11/2023 18:36:49 PM] Copied Log to clipboard
```
```


### Additional Information

_No response_

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoolCat467** [comment]
Might be related to #529

**Comment by RyanTheAllmighty** [comment]
Yeah this is a completely new mod loader that would be required to be implemented, not necessarily that the import is broken, it's because it's a new modloader that's not catered for
