### ISSUE TITLE
Large instance exports get rate limited by Modrinth

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#868]
### What happened?

Exporting an instance with a large number of mods can cause rate limits to be hit from Modrinth, causing the export to have issues, apparently missing mods

### Operating System

Windows

### Relevant log output

```shell
[08/01/2024 20:26:46 p.m.] com.atlauncher.network.DownloadException: https://api.modrinth.com/v2/project/yn9u3ypm/version?game_versions=["1.20.1"]&loaders=["fabric"] request wasn't successful: Response{protocol=http/1.1, code=429, message=Too Many Requests, url=https://api.modrinth.com/v2/project/yn9u3ypm/version?game_versions=[%221.20.1%22]&loaders=[%22fabric%22]}
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.execute(Download.java:334)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.asTypeWithThrow(Download.java:179)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.asType(Download.java:186)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.asType(Download.java:200)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.utils.ModrinthApi.getVersions(ModrinthApi.java:234)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.data.DisableableMod.lambda$checkForUpdate$11(DisableableMod.java:472)
[08/01/2024 20:26:46 p.m.] 	at java.base/java.lang.Thread.run(Unknown Source)
[08/01/2024 20:26:46 p.m.] com.atlauncher.network.DownloadException: https://api.modrinth.com/v2/project/yn9u3ypm/version?game_versions=["1.20.1"]&loaders=["fabric"] request wasn't successful: Response{protocol=http/1.1, code=429, message=Too Many Requests, url=https://api.modrinth.com/v2/project/yn9u3ypm/version?game_versions=[%221.20.1%22]&loaders=[%22fabric%22]}
	at com.atlauncher.network.Download.execute(Download.java:334)
	at com.atlauncher.network.Download.asTypeWithThrow(Download.java:179)
	at com.atlauncher.network.Download.asType(Download.java:186)
	at com.atlauncher.network.Download.asType(Download.java:200)
	at com.atlauncher.utils.ModrinthApi.getVersions(ModrinthApi.java:234)
	at com.atlauncher.data.DisableableMod.lambda$checkForUpdate$11(DisableableMod.java:472)
	at java.base/java.lang.Thread.run(Unknown Source)
[08/01/2024 20:26:46 p.m.] Date: Tue, 09 Jan 2024 02:26:46 GMT
Content-Type: application/json
Content-Length: 111
Connection: keep-alive
X-Ratelimit-Limit: 300
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 0
CF-Cache-Status: DYNAMIC
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 84293cbeddd92c98-DFW
[08/01/2024 20:26:46 p.m.] com.atlauncher.network.DownloadException: https://api.modrinth.com/v2/project/YDOf2ZPv request wasn't successful: Response{protocol=http/1.1, code=429, message=Too Many Requests, url=https://api.modrinth.com/v2/project/YDOf2ZPv}
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.execute(Download.java:334)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.asClassWithThrow(Download.java:140)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.asClass(Download.java:147)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.network.Download.asClass(Download.java:161)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.utils.ModrinthApi.getProject(ModrinthApi.java:188)
[08/01/2024 20:26:46 p.m.] 	at com.atlauncher.data.DisableableMod.lambda$checkForUpdate$11(DisableableMod.java:471)
[08/01/2024 20:26:46 p.m.] 	at java.base/java.lang.Thread.run(Unknown Source)
[08/01/2024 20:26:46 p.m.] com.atlauncher.network.DownloadException: https://api.modrinth.com/v2/project/YDOf2ZPv request wasn't successful: Response{protocol=http/1.1, code=429, message=Too Many Requests, url=https://api.modrinth.com/v2/project/YDOf2ZPv}
	at com.atlauncher.network.Download.execute(Download.java:334)
	at com.atlauncher.network.Download.asClassWithThrow(Download.java:140)
	at com.atlauncher.network.Download.asClass(Download.java:147)
	at com.atlauncher.network.Download.asClass(Download.java:161)
	at com.atlauncher.utils.ModrinthApi.getProject(ModrinthApi.java:188)
	at com.atlauncher.data.DisableableMod.lambda$checkForUpdate$11(DisableableMod.java:471)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by turabian-luvr** [comment]
I'm the guy who originally posted the issue in Discord. Modrinth support figured out what was wrong. Many mods were being erroneously marked as server-side-only in the mrpack's index json. Importing the instance directly into the Modrinth App (i.e. using its "Import From Launcher" button), then exporting the mrpack, fixed the issue.

**Comment by Doomsdayrs** [comment]
While it might have been an issue at Modrinth, I still think its important to find a solution.

If a server asks an application to slow down, a slow down should be respected.
