### ISSUE TITLE
Renaming an instant to an invalid name then launching it temporarily breaks it.

### ISSUE THREAD

**Issue by Phaxtolgia** [ATLauncher/ATLauncher#872]
### What happened?

1. Rename any instance with invalid characters. I renamed mine to "Custom Models (CPM & Figura)"
2. Launch the instance.
3. Witness crash/failure to launch
4. Click "Open Folder" and notice it opens to "This PC" instead.

Fortunately this is easy to fix. Simply re-launching ATLauncher seems to fix this issue.

### Operating System

Windows

### Relevant log output

```shell
[13/02/2024 13:06:19 PM] Showing Launcher
[13/02/2024 13:07:28 PM] Unknown Error Occurred While Renaming Instance!
[13/02/2024 13:07:34 PM] Preparing for launch!
[13/02/2024 13:07:34 PM] java.io.FileNotFoundException: **USERSDIR**\instances\CustomModelsCPMFigura\instance.json (The system cannot find the path specified)
[13/02/2024 13:07:34 PM] 	at java.io.FileOutputStream.open0(Native Method)
[13/02/2024 13:07:34 PM] 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[13/02/2024 13:07:34 PM] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[13/02/2024 13:07:34 PM] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[13/02/2024 13:07:34 PM] 	at com.atlauncher.data.Instance.save(Instance.java:2474)
[13/02/2024 13:07:34 PM] 	at com.atlauncher.data.Instance.prepareForLaunch(Instance.java:449)
[13/02/2024 13:07:34 PM] 	at com.atlauncher.data.Instance.lambda$launch$16(Instance.java:933)
[13/02/2024 13:07:34 PM] 	at java.lang.Thread.run(Thread.java:748)
[13/02/2024 13:07:35 PM] java.io.FileNotFoundException: **USERSDIR**\instances\CustomModelsCPMFigura\instance.json (The system cannot find the path specified)

	at java.io.FileOutputStream.open0(Native Method)

	at java.io.FileOutputStream.open(FileOutputStream.java:270)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)

	at com.atlauncher.data.Instance.save(Instance.java:2474)

	at com.atlauncher.data.Instance.prepareForLaunch(Instance.java:449)

	at com.atlauncher.data.Instance.lambda$launch$16(Instance.java:933)

	at java.lang.Thread.run(Thread.java:748)

[13/02/2024 13:07:36 PM] java.io.FileNotFoundException: **USERSDIR**\instances\CustomModelsCPMFigura\instance.json (The system cannot find the path specified)
[13/02/2024 13:07:36 PM] 	at java.io.FileOutputStream.open0(Native Method)
[13/02/2024 13:07:36 PM] 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[13/02/2024 13:07:36 PM] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[13/02/2024 13:07:36 PM] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[13/02/2024 13:07:36 PM] 	at com.atlauncher.data.Instance.save(Instance.java:2474)
[13/02/2024 13:07:36 PM] 	at com.atlauncher.data.Instance.launch(Instance.java:1286)
[13/02/2024 13:07:36 PM] 	at com.atlauncher.gui.card.InstanceCard.play(InstanceCard.java:608)
[13/02/2024 13:07:36 PM] 	at com.atlauncher.gui.card.InstanceCard.access$100(InstanceCard.java:77)
[13/02/2024 13:07:36 PM] 	at com.atlauncher.gui.card.InstanceCard$2.mousePressed(InstanceCard.java:107)
[13/02/2024 13:07:36 PM] 	at com.atlauncher.gui.components.DropDownButton$1.mousePressed(DropDownButton.java:55)
[13/02/2024 13:07:36 PM] 	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
[13/02/2024 13:07:36 PM] 	at java.awt.Component.processMouseEvent(Component.java:6536)
[13/02/2024 13:07:36 PM] 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
[13/02/2024 13:07:36 PM] 	at java.awt.Component.processEvent(Component.java:6304)
[13/02/2024 13:07:36 PM] 	at java.awt.Container.processEvent(Container.java:2239)
[13/02/2024 13:07:36 PM] 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
[13/02/2024 13:07:36 PM] 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
[13/02/2024 13:07:36 PM] 	at java.awt.Component.dispatchEvent(Component.java:4711)
[13/02/2024 13:07:36 PM] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
[13/02/2024 13:07:36 PM] 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
[13/02/2024 13:07:36 PM] 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
[13/02/2024 13:07:36 PM] 	at java.awt.Container.dispatchEventImpl(Container.java:2283)
[13/02/2024 13:07:36 PM] 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
[13/02/2024 13:07:36 PM] 	at java.awt.Component.dispatchEvent(Component.java:4711)
[13/02/2024 13:07:36 PM] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
[13/02/2024 13:07:36 PM] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[13/02/2024 13:07:36 PM] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[13/02/2024 13:07:36 PM] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[13/02/2024 13:07:36 PM] 	at java.security.AccessController.doPrivileged(Native Method)
[13/02/2024 13:07:36 PM] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
[13/02/2024 13:07:36 PM] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
[13/02/2024 13:07:36 PM] 	at java.awt.EventQueue$4.run(EventQueue.java:733)
[13/02/2024 13:07:36 PM] 	at java.awt.EventQueue$4.run(EventQueue.java:731)
[13/02/2024 13:07:36 PM] 	at java.security.AccessController.doPrivileged(Native Method)
[13/02/2024 13:07:36 PM] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
[13/02/2024 13:07:36 PM] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
[13/02/2024 13:07:36 PM] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
[13/02/2024 13:07:36 PM] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[13/02/2024 13:07:36 PM] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[13/02/2024 13:07:36 PM] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[13/02/2024 13:07:36 PM] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[13/02/2024 13:07:36 PM] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[13/02/2024 13:07:37 PM] java.io.FileNotFoundException: **USERSDIR**\instances\CustomModelsCPMFigura\instance.json (The system cannot find the path specified)

	at java.io.FileOutputStream.open0(Native Method)

	at java.io.FileOutputStream.open(FileOutputStream.java:270)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)

	at com.atlauncher.data.Instance.save(Instance.java:2474)

	at com.atlauncher.data.Instance.launch(Instance.java:1286)

	at com.atlauncher.gui.card.InstanceCard.play(InstanceCard.java:608)

	at com.atlauncher.gui.card.InstanceCard.access$100(InstanceCard.java:77)

	at com.atlauncher.gui.card.InstanceCard$2.mousePressed(InstanceCard.java:107)

	at com.atlauncher.gui.components.DropDownButton$1.mousePressed(DropDownButton.java:55)

	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)

	at java.awt.Component.processMouseEvent(Component.java:6536)

	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)

	at java.awt.Component.processEvent(Component.java:6304)

	at java.awt.Container.processEvent(Container.java:2239)

	at java.awt.Component.dispatchEventImpl(Component.java:4889)

	at java.awt.Container.dispatchEventImpl(Container.java:2297)

	at java.awt.Component.dispatchEvent(Component.java:4711)

	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)

	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)

	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)

	at java.awt.Container.dispatchEventImpl(Container.java:2283)

	at java.awt.Window.dispatchEventImpl(Window.java:2746)

	at java.awt.Component.dispatchEvent(Component.java:4711)

	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)

	at java.awt.EventQueue.access$500(EventQueue.java:97)

	at java.awt.EventQueue$3.run(EventQueue.java:709)

	at java.awt.EventQueue$3.run(EventQueue.java:703)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)

	at java.awt.EventQueue$4.run(EventQueue.java:733)

	at java.awt.EventQueue$4.run(EventQueue.java:731)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)

	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)

	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)

	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)

	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)

	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[13/02/2024 13:07:38 PM] Launching pack Minecraft 1.20.1 (Vanilla) for Minecraft 1.20.1
[13/02/2024 13:07:38 PM] Logging into Minecraft!
[13/02/2024 13:07:38 PM] Using Java runtime java-runtime-gamma (Java 17.0.3) at path **USERSDIR**\runtimes\minecraft\java-runtime-gamma\windows-x64\java-runtime-gamma
[13/02/2024 13:07:38 PM] Loader: Fabric 0.15.6
[13/02/2024 13:07:38 PM] java.lang.NullPointerException
[13/02/2024 13:07:38 PM] 	at com.atlauncher.mclauncher.MCLauncher.logInstanceInformation(MCLauncher.java:110)
[13/02/2024 13:07:38 PM] 	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:92)
[13/02/2024 13:07:38 PM] 	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:69)
[13/02/2024 13:07:38 PM] 	at com.atlauncher.data.Instance.lambda$launch$25(Instance.java:1063)
[13/02/2024 13:07:38 PM] 	at java.lang.Thread.run(Thread.java:748)
[13/02/2024 13:07:38 PM] java.lang.NullPointerException

	at com.atlauncher.mclauncher.MCLauncher.logInstanceInformation(MCLauncher.java:110)

	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:92)

	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:69)

	at com.atlauncher.data.Instance.lambda$launch$25(Instance.java:1063)

	at java.lang.Thread.run(Thread.java:748)

[13/02/2024 13:07:41 PM] Copied Log to clipboard
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
I cannot seem to replicate this issue no matter what I try and rename the instance to.

Does this happen every single time you rename an instance with something invalid, or only occasionally?

So create a new instance, try to rename it, does it fail every time you do that?
