### ISSUE TITLE
Can't launch game with abnormal version string libraries

### ISSUE THREAD

**Issue by a5632645** [ATLauncher/ATLauncher#919]
### What happened?

1.Open Atlauncher
2.Install minecraft 1.6.4 release with recommend forge
3.Launch game
4.Crash and game window not show

### Operating System

Windows

### Relevant log output

```shell
[16/06/2024 18:33:51 下午] java.lang.NumberFormatException: For input string: "1-nightly-20130708-debug3"
[16/06/2024 18:33:51 下午] 	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.lang.Integer.parseInt(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.lang.Integer.parseInt(Unknown Source)
[16/06/2024 18:33:51 下午] 	at com.atlauncher.utils.Utils.compareVersions(Utils.java:1542)
[16/06/2024 18:33:51 下午] 	at com.atlauncher.mclauncher.MCLauncher.lambda$getArguments$9(MCLauncher.java:220)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[16/06/2024 18:33:51 下午] 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[16/06/2024 18:33:51 下午] 	at com.atlauncher.mclauncher.MCLauncher.getArguments(MCLauncher.java:210)
[16/06/2024 18:33:51 下午] 	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:89)
[16/06/2024 18:33:51 下午] 	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:72)
[16/06/2024 18:33:51 下午] 	at com.atlauncher.data.Instance.lambda$launch$25(Instance.java:1062)
[16/06/2024 18:33:51 下午] 	at java.base/java.lang.Thread.run(Unknown Source)
[16/06/2024 18:33:52 下午] java.lang.NumberFormatException: For input string: "1-nightly-20130708-debug3"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at com.atlauncher.utils.Utils.compareVersions(Utils.java:1542)
	at com.atlauncher.mclauncher.MCLauncher.lambda$getArguments$9(MCLauncher.java:220)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.atlauncher.mclauncher.MCLauncher.getArguments(MCLauncher.java:210)
	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:89)
	at com.atlauncher.mclauncher.MCLauncher.launch(MCLauncher.java:72)
	at com.atlauncher.data.Instance.lambda$launch$25(Instance.java:1062)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Oops. Will fix this up shortly
