### ISSUE TITLE
MedevilMC MMC4 Not working 

### ISSUE THREAD

**Issue by zaeemx25** [ATLauncher/ATLauncher#924]
### What happened?

1) At first i installed MedevilMc using curseforge but it was having problems so i followded this post's https://github.com/LunaPixelStudios/Better-MC/issues/1538 advice to solve this in the last comment i followed the steps but still its still crashing. 

### Operating System

macOS

### Relevant log output

```shell
Time: 2024-07-07 02:54:55
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:558) ~[client-1.20.1-20230612.114412-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[client-1.20.1.jar:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "de.keksuccino.fancymenu.util.properties.PropertyContainerSet.getContainersOfType(String)" because "de.keksuccino.fancymenu.customization.ScreenCustomization.customizableScreens" is null
	at de.keksuccino.fancymenu.customization.ScreenCustomization.isCustomizationEnabledForScreen(ScreenCustomization.java:198) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23632!/:3.2.3] {re:mixin,re:classloading,pl:mixin:APP:drippyloadingscreen.mixins.json:client.MixinScreenCustomization from mod drippyloadingscreen,pl:mixin:A}
	at de.keksuccino.fancymenu.customization.ScreenCustomization.isCustomizationEnabledForScreen(ScreenCustomization.java:180) ~[fancymenu_forge_3.2.3_MC_1.20.1.jar%23632!/:3.2.3] {re:mixin,re:classloading,pl:mixin:APP:drippyloadingscreen.mixins.json:client.MixinScreenCustomization from mod drippyloadingscreen,pl:mixin:A}
	at de.keksuccino.drippyloadingscreen.customization.DrippyOverlayScreen.forceEnableCustomizations(DrippyOverlayScreen.java:42) ~[drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar%23610!/:3.0.1] {re:mixin,re:classloading}
	at de.keksuccino.drippyloadingscreen.customization.DrippyOverlayScreen.<init>(DrippyOverlayScreen.java:38) ~[drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar%23610!/:3.0.1] {re:mixin,re:classloading}
	at net.minecraft.client.gui.screens.LoadingOverlay.<clinit>(LoadingOverlay.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23869!/:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:fancymenu.mixins.json:client.MixinLoadingOverlay from mod fancymenu,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinLoadingOverlay from mod drippyloadingscreen,pl:mixin:APP:drippyloadingscreen.mixins.json:client.MixinLoadingOverlay from mod drippyloadingscreen,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	... 17 more
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zaeemx25** [comment]
[crash-2024-07-07_02.54.54-client.txt](https://github.com/user-attachments/files/16117471/crash-2024-07-07_02.54.54-client.txt)
This is my crash report
