### ISSUE TITLE
error loading instance

### ISSUE THREAD

**Issue by JasimAlrawie** [ATLauncher/ATLauncher#948]
### What happened?

# how it happen
open ATLauncher 
start an instance
then showing 
![image](https://github.com/user-attachments/assets/eac70045-397c-4dd2-beec-8a9e3e05abc1)
this forever
sometimes it says downloading 0.3MB or 3MB i dont remeber

also when i want to install other version and i check fabric it keep loading forever

# But
these thigs won't happen if i use VPN such as 1.1.1.1

### Operating System

Windows

### Relevant log output

```shell
[23/08/2024 23:44:09 PM] Console Cleared
[23/08/2024 23:44:11 PM] Failed to send data to paste API
[23/08/2024 23:44:11 PM] java.net.ConnectException: Connection timed out: connect
[23/08/2024 23:44:11 PM] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[23/08/2024 23:44:11 PM] 	at java.base/sun.nio.ch.Net.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.nio.ch.Net.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/java.net.Socket.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
[23/08/2024 23:44:11 PM] 	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:63)
[23/08/2024 23:44:11 PM] 	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:36)
[23/08/2024 23:44:11 PM] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23/08/2024 23:44:11 PM] 	at java.base/java.lang.Thread.run(Unknown Source)
[23/08/2024 23:44:11 PM] java.net.ConnectException: Connection timed out: connect

	at java.base/sun.nio.ch.Net.connect0(Native Method)

	at java.base/sun.nio.ch.Net.connect(Unknown Source)

	at java.base/sun.nio.ch.Net.connect(Unknown Source)

	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)

	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)

	at java.base/java.net.Socket.connect(Unknown Source)

	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)

	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)

	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)

	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)

	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)

	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)

	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)

	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)

	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)

	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)

	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)

	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)

	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:63)

	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:36)

	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

[23/08/2024 23:44:12 PM] Preparing for launch!
[23/08/2024 23:44:33 PM] java.net.ConnectException: Failed to connect to maven.fabricmc.net/188.114.97.7:443
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[23/08/2024 23:44:33 PM] 	at com.atlauncher.network.DebugLoggingInterceptor.intercept(DebugLoggingInterceptor.java:46)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[23/08/2024 23:44:33 PM] 	at com.atlauncher.network.Download.execute(Download.java:328)
[23/08/2024 23:44:33 PM] 	at com.atlauncher.network.Download.getFilesize(Download.java:410)
[23/08/2024 23:44:33 PM] 	at com.atlauncher.network.Download.needToDownload(Download.java:459)
[23/08/2024 23:44:33 PM] 	at com.atlauncher.network.DownloadPool.totalSize(DownloadPool.java:67)
[23/08/2024 23:44:33 PM] 	at com.atlauncher.data.Instance.prepareForLaunch(Instance.java:580)
[23/08/2024 23:44:33 PM] 	at com.atlauncher.data.Instance.lambda$launch$16(Instance.java:932)
[23/08/2024 23:44:33 PM] 	at java.base/java.lang.Thread.run(Unknown Source)
[23/08/2024 23:44:33 PM] 	Suppressed: java.net.ConnectException: Failed to connect to maven.fabricmc.net/188.114.96.7:443
[23/08/2024 23:44:33 PM] 		... 25 more
[23/08/2024 23:44:33 PM] 	Caused by: java.net.ConnectException: Connection timed out: no further information
[23/08/2024 23:44:33 PM] 		at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[23/08/2024 23:44:33 PM] 		at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
[23/08/2024 23:44:33 PM] 		at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
[23/08/2024 23:44:33 PM] 		at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:33 PM] 		at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:33 PM] 		at java.base/java.net.Socket.connect(Unknown Source)
[23/08/2024 23:44:33 PM] 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
[23/08/2024 23:44:33 PM] 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
[23/08/2024 23:44:33 PM] 		... 24 more
[23/08/2024 23:44:33 PM] Caused by: java.net.ConnectException: Connection timed out: no further information
[23/08/2024 23:44:33 PM] 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[23/08/2024 23:44:33 PM] 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
[23/08/2024 23:44:33 PM] 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
[23/08/2024 23:44:33 PM] 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:33 PM] 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
[23/08/2024 23:44:33 PM] 	at java.base/java.net.Socket.connect(Unknown Source)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
[23/08/2024 23:44:33 PM] 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
[23/08/2024 23:44:33 PM] 	... 24 more
[23/08/2024 23:44:33 PM] java.net.ConnectException: Failed to connect to maven.fabricmc.net/188.114.97.7:443

	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)

	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)

	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)

	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)

	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)

	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)

	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

	at com.atlauncher.network.DebugLoggingInterceptor.intercept(DebugLoggingInterceptor.java:46)

	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)

	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)

	at com.atlauncher.network.Download.execute(Download.java:328)

	at com.atlauncher.network.Download.getFilesize(Download.java:410)

	at com.atlauncher.network.Download.needToDownload(Download.java:459)

	at com.atlauncher.network.DownloadPool.totalSize(DownloadPool.java:67)

	at com.atlauncher.data.Instance.prepareForLaunch(Instance.java:580)

	at com.atlauncher.data.Instance.lambda$launch$16(Instance.java:932)

	at java.base/java.lang.Thread.run(Unknown Source)

	Suppressed: java.net.ConnectException: Failed to connect to maven.fabricmc.net/188.114.96.7:443

		... 25 more

	Caused by: java.net.ConnectException: Connection timed out: no further information

		at java.base/sun.nio.ch.Net.pollConnect(Native Method)

		at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)

		at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)

		at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)

		at java.base/java.net.SocksSocketImpl.connect(Unknown Source)

		at java.base/java.net.Socket.connect(Unknown Source)

		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)

		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)

		... 24 more

Caused by: java.net.ConnectException: Connection timed out: no further information

	at java.base/sun.nio.ch.Net.pollConnect(Native Method)

	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)

	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)

	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)

	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)

	at java.base/java.net.Socket.connect(Unknown Source)

	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)

	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)

	... 24 more

[23/08/2024 23:44:35 PM] Failed to prepare instance 1.21.1 for launch. Check the logs and try again.
[23/08/2024 23:44:46 PM] Copied Log to clipboard
```

### Additional Information

# what i try

* i removed the libs from the launcher and redownload it **NO-FIX**
* i uninstalled and reinstalled ATLauncher **NO-FIX**
* i checked firewall nothing wrong **NO-FIX**
* i checked event viewer for any error **NO-FIX**

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasimAlrawie** [comment]
another thing to mention
ATLauncher website also doesnt load if i dont use VPN :(
