### ISSUE TITLE
ATLauncher can't find an archive of the modpack from CurseForge

### ISSUE THREAD

**Issue by gigaVova** [ATLauncher/ATLauncher#971]
### What happened?

1. Open ATLauncher
2. Go to "Packs"
3. Search for "Mineshafts & Monsters"
4. "Install"
5. The launcher asked me to download the archive named `Mineshafts Monsters - 1.11.zip`
6. The webpage was opened, the archive was downloaded to the Downloads folder that is specified by the launcher (both ATLauncher's and system standart)
7. Press "I've downloaded this file", and after that the sixth step repeats

I expect at least an error, but the archive is just not found by the launcher

### Operating System

Windows

### Relevant log output

```shell
[27/10/2024 19:06:39 PM] Started install of Mineshafts & Monsters version Mineshafts & Monsters - 1.11
[27/10/2024 19:07:27 PM] java.lang.NullPointerException: Cannot invoke "com.atlauncher.data.json.Version.getMinecraft()" because "this.packVersion" is null
[27/10/2024 19:07:27 PM] 	at com.atlauncher.workers.InstanceInstaller.downloadMinecraftVersionJson(InstanceInstaller.java:1728)
[27/10/2024 19:07:27 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:328)
[27/10/2024 19:07:27 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:139)
[27/10/2024 19:07:27 PM] 	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
[27/10/2024 19:07:27 PM] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[27/10/2024 19:07:27 PM] 	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
[27/10/2024 19:07:27 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[27/10/2024 19:07:27 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[27/10/2024 19:07:27 PM] 	at java.base/java.lang.Thread.run(Unknown Source)
[27/10/2024 19:07:27 PM] java.lang.NullPointerException: Cannot invoke "com.atlauncher.data.json.Version.getMinecraft()" because "this.packVersion" is null
	at com.atlauncher.workers.InstanceInstaller.downloadMinecraftVersionJson(InstanceInstaller.java:1728)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:328)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:139)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Not an issue for me, doesn't seem to be a launcher issue given it's working for me. I suggest you visit our Discord at https://atl.pw/discord so that we can help you further.

Again, as this is not reproducible, will close this and provide further support via Discord

**Comment by gigaVova** [comment]
Found out that this issue is connected to using a firefox-based browser (Zen in my case). I tried chromium-based browser, and ATLauncher found the archive without errors. Interesting, that mods, that must be downloaded by hands, can be downloaded from firefox-based browser and the launcher will find them.
