### ISSUE TITLE
Rate limit issues when downloading from minecraft.net

### ISSUE THREAD

**Issue by TimCargan** [ATLauncher/ATLauncher#976]
### What happened?

When installing a new instance the download from `resources.download.minecraft.net` triggers a http 429 too many requests error (see the logs) causing the install to fail. I was able to get around this by using a mobile hotspot with a slower connection. Maybe there is some retry logic missing? 

### Operating System

macOS

### Relevant log output

```shell
[19/11/2024 19:38:24 pm] Started install of Fabulously Optimized version 6.4.0-alpha.8 for 1.21.3 (6.4.0-alpha.8)
[19/11/2024 19:38:27 pm] Date: Tue, 19 Nov 2024 19:38:27 GMT
Content-Type: text/html
Content-Length: 1261
Connection: close
Cache-Control: no-store
x-azure-ref: 20241119T193827Z-r1559f78f6bk4m56hC1LONaw5w00000006wg00000003vp3q
X-Cache: CONFIG_NOCACHE
[19/11/2024 19:38:27 pm] Error trying to download 65919863c0a6fbb0ae175f1b2d9061532b1fd725
[19/11/2024 19:38:27 pm] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/65/65919863c0a6fbb0ae175f1b2d9061532b1fd725 request wasn't successful: Response{protocol=http/1.1, code=429, message=Too Many Requests, url=https://resources.download.minecraft.net/65/65919863c0a6fbb0ae175f1b2d9061532b1fd725}
[19/11/2024 19:38:27 pm] 	at com.atlauncher.network.Download.execute(Download.java:334)
[19/11/2024 19:38:27 pm] 	at com.atlauncher.network.Download.downloadFile(Download.java:620)
[19/11/2024 19:38:27 pm] 	at com.atlauncher.network.Download.downloadFile(Download.java:576)
[19/11/2024 19:38:27 pm] 	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
[19/11/2024 19:38:27 pm] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19/11/2024 19:38:27 pm] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19/11/2024 19:38:27 pm] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[19/11/2024 19:38:27 pm] com.atlauncher.network.DownloadException: https://resources.download.minecraft.net/65/65919863c0a6fbb0ae175f1b2d9061532b1fd725 request wasn't successful: Response{protocol=http/1.1, code=429, message=Too Many Requests, url=https://resources.download.minecraft.net/65/65919863c0a6fbb0ae175f1b2d9061532b1fd725}
	at com.atlauncher.network.Download.execute(Download.java:334)
	at com.atlauncher.network.Download.downloadFile(Download.java:620)
	at com.atlauncher.network.Download.downloadFile(Download.java:576)
	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
Yeah we've attempted to fix this in the past with #771 but still comes back.

People who run into this say they get the same response on the same file for hours, even days, so that's why there's no retry logic. 

Attempts to replicate the issue to look at a fix have never worked, so this one is very hard for us to fix
