### ISSUE TITLE
NeoForge ServerStarterJar not working

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#977]
### What happened?

1. Install Pixelmon Modpack server from Modrinth
2. Try to run that server from the launcher
3. Alternatively open the folder for the server and run `java -jar server.jar`
4. Expect the server to start, but it just errors out

### Operating System

Windows

### Relevant log output

```shell
❯ java -jar server.jar             
Exception in thread "main" java.lang.IllegalStateException: Could not find parent layer for module `jdk.jstatd` read by `net.minecraftforge.mergetool.api`
        at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.<init>(SecureModuleClassLoader.java:137)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.<init>(ModuleClassLoader.java:29)
        at net.minecraftforge.bootstrap@1.2.0/net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at net.neoforged.serverstarterjar.Main.mainLaunch(Main.java:266)
        at net.neoforged.serverstarterjar.Main.main(Main.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at net.neoforged.serverstarterjar.Main8.main(Main8.java:19)


----

"C:\Users\****\AppData\Roaming\ATLauncher\runtimes\minecraft\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\java.exe"  -jar server.jar  nogui

Exception in thread "main" java.lang.IllegalStateException: Could not find parent layer for module `jdk.internal.ed` read by `io.netty.handler`
        at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.<init>(SecureModuleClassLoader.java:137)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.<init>(ModuleClassLoader.java:29)
        at net.minecraftforge.bootstrap@1.2.0/net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.neoforged.serverstarterjar.Main.mainLaunch(Main.java:266)
        at net.neoforged.serverstarterjar.Main.main(Main.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.neoforged.serverstarterjar.Main8.main(Main8.java:19)
```

### Additional Information

Doesn't seem to matter if using the java runtimes or java from the system (in my case which is the top log output) I use the below:

openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment (build 17.0.13+11)
OpenJDK 64-Bit Server VM (build 17.0.13+11, mixed mode, sharing)

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevashley92** [comment]
I am also seeing the same issue trying to run a server from the launcher.  Something to note that the error content appears to be different every time I try to launch, with the caveat being that its always the same error format:

"Exception in thread "main" java.lang.IllegalStateException: Could not find parent layer for module '<SOME MODULE>' read by '<SOMETHING ELSE>'"
